import { CardType, Domain, SkillCard } from "../types";

export const SYSTEM_SKILL_CARDS: Record<string, SkillCard> = {
	"ARCANA-10-1": {
		id: "ARCANA-10-1",
		title: "Adjust Reality",
		description:
			"After a dice roll you or a willing ally makes, you may spend <b>5 Hope</b> to change the results of that roll to a result of your choice instead. The result must be plausible within the range of the dice.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-7-1": {
		id: "ARCANA-7-1",
		title: "Arcana Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Arcana domain: \n<ul><li>Gain +1 to your Spellcast rolls.</li><li>Once per short rest, switch the values on your Hope and Fear die.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-1": {
		id: "ARCANA-8-1",
		title: "Arcane Reflection",
		description:
			"Whenever you would take magic damage, if you choose not to reduce it using <b>Armor</b>, you may spend a *Hope* to roll an amount of *d6* equal to your *Spellcast Trait*. If any of the dice roll a result of *6*, the attack is reflected back onto the caster, dealing the damage to them instead.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-4-1": {
		id: "ARCANA-4-1",
		title: "Blink Out",
		description:
			"Make a *Spellcast Roll (12)*. On a success, spend a *Hope* and vanish, teleporting to another place you can see within very far range. If any creatures are very close to you when you succeed, you can spend an additional *Hope* each to bring them with you.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-5-1": {
		id: "ARCANA-5-1",
		title: "Chain Lightning",
		description:
			"Once per short rest, make a *Spellcast Roll* against every adversary in front of you within close range. On a success, the GM must make a *Reaction Roll (16)* for the targets. On a failure, they take *3d8* plus a number of *d8*s equal to your *Spellcast Trait* in magic damage. On a success, they take half damage (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-2-1": {
		id: "ARCANA-2-1",
		title: "Cinder Grasp",
		description:
			"Make a *Spellcast Roll* against a target in melee range. On a success, the target instantly bursts into flames, dealing *1d20* magic damage and temporarily catching them on fire.\nAny time a creature tries to act while on fire, it must take an additional *2d6* magic damage if it is still on fire at the end of its action.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-7-2": {
		id: "ARCANA-7-2",
		title: "Cloaking Blast",
		description:
			"Make an *Attack Roll* using your primary weapon against a target. On a success, along with dealing damage, you can also spend a *Hope* to immediately become hidden.\nHidden only drops the next time you make an action roll or the GM uses all of the tokens on the action tracker.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-2": {
		id: "ARCANA-8-2",
		title: "Confusing Aura",
		description:
			"Make a *Spellcast Roll (14)*. Once per *long rest*, on a success you create a layer of illusion over your body that makes it hard to tell exactly where you are. You may mark any number of *stress* to make that many additional layers. When an adversary makes an attack against you, roll a number of *d6* equal to the number of layers currently active. If any land on a *4+*, one layer of the aura is destroyed and you avoid the attack. If all are *3-*, you take the damage and the effect ends.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-3-1": {
		id: "ARCANA-3-1",
		title: "Counterspell",
		description:
			"Once per *short rest*, you can interrupt a spell or magical effect that is taking place to make a *Reaction Roll* using your *Spellcast* trait. On a success, the spell or effect is immediately stopped and any consequences are avoided.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-9-1": {
		id: "ARCANA-9-1",
		title: "Earthquake",
		description:
			"Make a *Spellcast Roll (16)*. Once per *short rest*, on a success all creatures within *very far range* of your choice must make a *Reaction Roll (18)*. On a failure, they take *3d10* _physical damage_ and are *Vulnerable*. On a success, they take half damage (rounded up).\n\nWhen you successfully cast this spell, all terrain within *very far range* of you becomes *difficult* to move through, and structures within this range may sustain damage or crumble.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-10-2": {
		id: "ARCANA-10-2",
		title: "Falling Sky",
		description:
			"Make a *Spellcast Roll* against all enemies within far range. Mark any number of *Stress* to make shards of arcana rain down from above, dealing *1d20* damage per each *Stress* you marked to any targets you succeed against.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-3-2": {
		id: "ARCANA-3-2",
		title: "Flight",
		description:
			"Mark a *Stress* to take flight for a number of minutes equal to your level. While flying, you may spend a *Hope* to pick up and carry another creature approximately your size or smaller. You cannot carry more than one other creature at a time.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-2-2": {
		id: "ARCANA-2-2",
		title: "Floating Eye",
		description:
			"You can spend a *Hope* to create a single, small floating orb that you can control anywhere within very far range from you. While controlling it, you can choose to see through its vision as though it's your own. If the orb takes damage or moves out of range, the spell will immediately end.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-5-2": {
		id: "ARCANA-5-2",
		title: "Premonition",
		description:
			"You can channel the arcane energy to have visions of the future. Once per long rest, immediately after the GM conveys the consequences of you rolling with *Fear*, you may make that event your Premonition. You instead rescind the action and consequences like they never happened and choose another action instead.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-4-2": {
		id: "ARCANA-4-2",
		title: "Preservation Blast",
		description:
			"Make a *Spellcast Roll* against all enemies within melee range of you. Any you succeed against are hurdled into far range and dealt *d8* magic damage using your Spellcast Trait.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-6-1": {
		id: "ARCANA-6-1",
		title: "Rift Walker",
		description:
			"Once per long rest, on a successful *Spellcast Roll (15)* you place an arcane marking upon the ground where you currently stand. The next time you successfully cast *Rift Walker* with a *Spellcast Roll (15)*, a rift in space will open up, providing safe passage back to the exact spot where the marking was placed. You may drop the marking at anytime to cast *Rift Walker* again and place it somewhere new.\nThis rift stays open until you choose to close it or you cast another spell.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-1": {
		id: "ARCANA-1-1",
		title: "Rune Ward",
		description:
			"You have a deeply personal token or trinket that can be infused with protective magic and held as a ward by you or an ally. Describe what it is and why it's important to you. When the holder of the ward takes damage, they can *spend Hope* to reduce it by *1d8*.\nIf the ward die rolls an *8*, its power will temporarily end after it reduces damage this turn. It can be recharged for free on your next rest.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-9-2": {
		id: "ARCANA-9-2",
		title: "Sensory Projection",
		description:
			"Once per short rest, make a *Spellcast Roll (15)*. On a success, drop into a vision that lets you clearly see and hear any place you have been before in this moment as though you are standing there. You can move freely in this vision and are not constrained by the physics or impediments of a physical body. This spell cannot be detected by mundane or magical means and you will drop out of this vision immediately upon taking damage or casting another spell.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-6-2": {
		id: "ARCANA-6-2",
		title: "Telekinesis",
		description:
			"Make a *Spellcast Roll* against an object or target within far range. On a success, you can move it anywhere within far range of its current position using only your mind. If the target is unwilling, you must spend *1* or more *Stress* to do so, and can deal *1d20* magic damage per *Stress* spent. If you are hitting a creature with the target, divide the damage equally between the two.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-2": {
		id: "ARCANA-1-2",
		title: "Unleash Chaos",
		description:
			"At the beginning of a session, place a number of tokens equal to your Spellcast Trait on this card.\nYou can make a *Spellcast Roll* against a target within far range and spend any number of tokens to channel raw energy from within yourself and unleash against them. On a success, roll a number of *d10* equal to the tokens you spent, and do that much magic damage to the target. Mark a *Stress* to replenish this card with tokens, up to your *Spellcast Trait*. Clear all tokens at the end of the session.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-1-3": {
		id: "ARCANA-1-3",
		title: "Wall Walk",
		description:
			"Spend a *Hope* to allow a creature you can touch to climb on walls and ceilings as easily as walking on the ground below. This spell will end after ten minutes or when you cast it on another creature.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-1": {
		id: "BLADE-1-1",
		title: "Not Good Enough",
		description:
			"When you roll your damage dice, you may reroll any *1s* or *2s*. If you do, you must take the new result, even on a *1* or *2*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-2": {
		id: "BLADE-1-2",
		title: "Retaliation",
		description:
			"When you take damage from a creature in melee range, you may mark a *Stress* to immediately deal weapon damage to the creature at half *Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-3": {
		id: "BLADE-1-3",
		title: "Whirlwind",
		description:
			"When you make a successful attack using a weapon with melee or very close range, you may also spend a *Hope* to use that roll against every other enemy in that weapon's range. Any additional enemies you succeed against with this ability take half damage (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-2-1": {
		id: "BLADE-2-1",
		title: "A Soldier's Bond",
		description:
			"Once per long rest, if you compliment someone or ask them about something they are good at, you may both take *3 Hope*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-2-2": {
		id: "BLADE-2-2",
		title: "Reckless",
		description:
			"You may always mark a *Stress* to take _advantage_ on an *Attack Roll* against a target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-3-1": {
		id: "BLADE-3-1",
		title: "Scramble",
		description:
			"Once per short rest, when an enemy in melee range would deal damage to you, you can avoid the damage entirely and safely move out of melee range of the enemy.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-3-2": {
		id: "BLADE-3-2",
		title: "Versatile Fighter",
		description:
			"You can choose to use the Character Trait of your choice on an equipped weapon, rather than the trait the weapon calls for.\nWhen dealing damage, you may mark a *Stress* to take the maximum value of one of your *Damage Die* instead of rolling it.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-4-1": {
		id: "BLADE-4-1",
		title: "Deadly Focus",
		description:
			"Once per short rest, you can apply all your focus towards a single target. Choose that target. Until you attack another target, you defeat the creature, or the battle ends, add *+1* to your *Proficiency*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-4-2": {
		id: "BLADE-4-2",
		title: "Fortified Armor",
		description:
			"Increase your *Armor Score* by *+2* while you are wearing armor and this card is in your loadout. Once per short rest, you may use an Armor Slot without marking it.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-5-1": {
		id: "BLADE-5-1",
		title: "Hero's Strike",
		description:
			"When you land a critical hit on an *Attack Roll*, choose two of the following:<ul><li>Clear a Hit Point.</li><li>Clear a marked Armor Slot.</li><li>Mark +1 Hit Point on the target of the attack.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-5-2": {
		id: "BLADE-5-2",
		title: "Prowess",
		description:
			"*When you take this card, choose two:*<ul><li>Permanently add one additional *Stress* slot</li><li>Permanently add one additional *Hit Point Slot*</li><li>Permanently raise your *Minor Damage Threshold to 5*. Any damage that comes in below this value does not mark any hit points.</li></ul>\nThen place it into your Vault *permanently.*",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-6-1": {
		id: "BLADE-6-1",
		title: "Battle Hardened",
		description:
			"Once per long rest, when you mark your final Hit Point, instead of making a death move, you can choose to automatically take a *Scar* (permanently cross out one *Hope Slot*), and roll *1d6*. Clear that many Hit Points and stay on your feet.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-6-2": {
		id: "BLADE-6-2",
		title: "Rage Up",
		description:
			"Before making an *Attack Roll*, you may mark a *Stress* to temporarily increase your Proficiency by *+1* until the end of the attack.\nYou may Rage Up twice per *Attack Roll*.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-7-1": {
		id: "BLADE-7-1",
		title: "Battle Touched",
		description:
			"When a majority of the domain cards in your *loadout* are from the *Blade* domain:<ul><li>*Attack Rolls always* take *+2* to their result.</li><li>Increase your *Severe Damage Threshold* by *+4*.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-7-2": {
		id: "BLADE-7-2",
		title: "Glancing Blow",
		description:
			"Whenever you make an attack that misses its target, you may mark a *Stress* to still hit the target for weapon damage at half Proficiency (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-8-1": {
		id: "BLADE-8-1",
		title: "Battle Cry",
		description:
			"Once per short rest, while you are charging into danger, you can muster a rousing shout or phrase that inspires your allies. You and all your allies that can hear you each clear a *Stress*, gain a *Hope*, and until you or an ally fails a roll with *Fear*, gain *+1* Proficiency.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-8-2": {
		id: "BLADE-8-2",
		title: "Frenzy",
		description:
			"Once per long rest, you can go into a *frenzied state* until there are no more threats within sight.\nWhile *frenzied*, you cannot use *Armor Slots*, you have *+2* to your *Proficiency*, and your *Severe Damage Threshold* is increased by *+8*.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-9-1": {
		id: "BLADE-9-1",
		title: "Gore and Glory",
		description:
			"Whenever you deal enough Weapon damage to defeat an enemy, you can gain a *Hope* or clear a *Stress*. When you roll a Critical Success on a weapon attack, you gain an additional *Hope* or clear an additional *Stress*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-9-2": {
		id: "BLADE-9-2",
		title: "Reaper Strike",
		description:
			"You may declare you are using *Reaper Strike*. Spend a *Hope* and make an *Attack Roll*. The GM will tell you any enemy it would succeed against in range of your weapon. Once per long rest, choose one of these enemies, and immediately deal *5 Hit Points* of damage to them.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-10-1": {
		id: "BLADE-10-1",
		title: "Battle Monster",
		description:
			"When you make a successful attack against an enemy, instead of rolling for damage you may spend *6 Hope* to deal the target a number of *Hit Points* equal to the amount of *Hit Points* you currently have marked.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BLADE-10-2": {
		id: "BLADE-10-2",
		title: "Onslaught",
		description:
			"When you successfully hit, your weapon attacks never deal damage beneath a target's *Major Damage Threshold* (you will always deal a minimum of *2 Hit Points* of damage).\nIn addition, whenever an enemy within weapon range deals damage to an ally with an attack that doesn't include you, you can mark a *Stress* to immediately deal weapon damage to the enemy at *half Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BONE-1-1": {
		id: "BONE-1-1",
		title: "Deft Maneuvers",
		description:
			"You can mark a *Stress* to move anywhere within far range without making an *Agility Roll* to get there.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-2": {
		id: "BONE-1-2",
		title: "I see it coming",
		description:
			"When you are targeted by a ranged attack, mark a *Stress* to roll a *d6* and increase your *Evasion* against this attack by its value.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-3": {
		id: "BONE-1-3",
		title: "Nimble",
		description:
			"While this card is in your loadout, add half of your Agility score to your Evasion (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-2-1": {
		id: "BONE-2-1",
		title: "Ferocity",
		description:
			"When you cause an enemy to mark any Hit Points, spend a *Hope* to temporarily increase your *Evasion* by the number of *Hit Points* you dealt. This bonus lasts until after the next attack that targets you.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
	"BONE-2-2": {
		id: "BONE-2-2",
		title: "Strategic Approach",
		description:
			"After a long rest, place a number of tokens equal to your Knowledge Trait on this card, with a minimum of *1*. When you move into melee range of an enemy and make an *Attack Roll* against them, you may spend one token to choose an option below.<ul><li>Make the attack at advantage.</li><li>Don't add a character token to the action tracker for this attack.</li><li>Add 1d8 to your damage.</li></ul>\n\nWhen you take a long rest, clear all unused tokens.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
  "BONE-3-1": {
		id: "BONE-3-1",
		title: "Brace",
		description:
			"When you use an Armor Slot to reduce incoming damage, you may also spend any number of *Hope*. For every *Hope* you spend, reduce the incoming damage by the value of your *Proficiency*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
	"BONE-3-2": {
		id: "BONE-3-2",
		title: "Tactician",
		description:
			"When you *Help* an *Ally*, they can add one of your *Experience* to their roll as well. When making a *Tag Team* roll, you can roll a *d20* for your *Hope* die instead of a *d12*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
  "BONE-4-1": {
		id: "BONE-4-1",
		title: "Boost",
		description:
			"If you have an ally in close range of you, mark a *Stress* to boost off of them and into the air to perform an aerial attack at an enemy within far range. You have advantage on the attack, add *1d10* to the damage, and end your action in melee range of the target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
	"BONE-4-2": {
		id: "BONE-4-2",
		title: "Redirect",
		description:
			"When you successfully evade a ranged attack, you may roll a number of *d6* equal to your proficiency. If any roll a *6*, mark a *Stress* to redirect the attack to instead damage an enemy within very close range of you.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
  "BONE-5-1": {
		id: "BONE-5-1",
		title: "Know thy Enemy",
		description:
			"When observing a creature, you can make a *Instinct Roll* against the target. On a success, spend a *Hope* and ask the GM for two of the mechanical specifics about the target from below:<ul><li>Current Hit Points and unmarked stress.</li><li>Difficulty and Damage Thresholds.</li><li>Their Tactics and standard attack Damage Dice.</li><li>Their Moves and Experiences.</li></ul>\nOn a success, you may also mark a *Stress* to remove one *Fear* from the GM's *Fear Pool*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
	"BONE-5-2": {
		id: "BONE-5-2",
		title: "Signature Move",
		description:
			"You take on a signature move in battle that you can perform once per short rest. Name it and describe it. When you include its description in an action you're taking, use a *d20* instead of a *d12* as your *Hope* die. If the attack succeeds, you may clear a *Stress*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
};
