import { CardType, Domain, SkillCard } from "../types";

export const SYSTEM_SKILL_CARDS: Record<string, SkillCard> = {
	"ARCANA-10-1": {
		id: "ARCANA-10-1",
		title: "Adjust Reality",
		description:
			"After a dice roll you or a willing ally makes, you may spend <b>5 Hope</b> to change the results of that roll to a result of your choice instead. The result must be plausible within the range of the dice.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-7-1": {
		id: "ARCANA-7-1",
		title: "Arcana Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Arcana domain: \n<ul><li>Gain +1 to your Spellcast rolls.</li><li>Once per short rest, switch the values on your Hope and Fear die.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-1": {
		id: "ARCANA-8-1",
		title: "Arcane Reflection",
		description:
			"Whenever you would take magic damage, if you choose not to reduce it using <b>Armor</b>, you may spend a *Hope* to roll an amount of *d6* equal to your *Spellcast Trait*. If any of the dice roll a result of *6*, the attack is reflected back onto the caster, dealing the damage to them instead.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-4-1": {
		id: "ARCANA-4-1",
		title: "Blink Out",
		description:
			"Make a *Spellcast Roll (12)*. On a success, spend a *Hope* and vanish, teleporting to another place you can see within very far range. If any creatures are very close to you when you succeed, you can spend an additional *Hope* each to bring them with you.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-5-1": {
		id: "ARCANA-5-1",
		title: "Chain Lightning",
		description:
			"Once per short rest, make a *Spellcast Roll* against every adversary in front of you within close range. On a success, the GM must make a *Reaction Roll (16)* for the targets. On a failure, they take *3d8* plus a number of *d8*s equal to your *Spellcast Trait* in magic damage. On a success, they take half damage (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-2-1": {
		id: "ARCANA-2-1",
		title: "Cinder Grasp",
		description:
			"Make a *Spellcast Roll* against a target in melee range. On a success, the target instantly bursts into flames, dealing *1d20* magic damage and temporarily catching them on fire.\nAny time a creature tries to act while on fire, it must take an additional *2d6* magic damage if it is still on fire at the end of its action.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-7-2": {
		id: "ARCANA-7-2",
		title: "Cloaking Blast",
		description:
			"Make an *Attack Roll* using your primary weapon against a target. On a success, along with dealing damage, you can also spend a *Hope* to immediately become hidden.\nHidden only drops the next time you make an action roll or the GM uses all of the tokens on the action tracker.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-2": {
		id: "ARCANA-8-2",
		title: "Confusing Aura",
		description:
			"Make a *Spellcast Roll (14)*. Once per *long rest*, on a success you create a layer of illusion over your body that makes it hard to tell exactly where you are. You may mark any number of *stress* to make that many additional layers. When an adversary makes an attack against you, roll a number of *d6* equal to the number of layers currently active. If any land on a *4+*, one layer of the aura is destroyed and you avoid the attack. If all are *3-*, you take the damage and the effect ends.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-3-1": {
		id: "ARCANA-3-1",
		title: "Counterspell",
		description:
			"Once per *short rest*, you can interrupt a spell or magical effect that is taking place to make a *Reaction Roll* using your *Spellcast* trait. On a success, the spell or effect is immediately stopped and any consequences are avoided.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-9-1": {
		id: "ARCANA-9-1",
		title: "Earthquake",
		description:
			"Make a *Spellcast Roll (16)*. Once per *short rest*, on a success all creatures within *very far range* of your choice must make a *Reaction Roll (18)*. On a failure, they take *3d10* <i>physical damage</i> and are *Vulnerable*. On a success, they take half damage (rounded up).\n\nWhen you successfully cast this spell, all terrain within *very far range* of you becomes *difficult* to move through, and structures within this range may sustain damage or crumble.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-10-2": {
		id: "ARCANA-10-2",
		title: "Falling Sky",
		description:
			"Make a *Spellcast Roll* against all enemies within far range. Mark any number of *Stress* to make shards of arcana rain down from above, dealing *1d20* damage per each *Stress* you marked to any targets you succeed against.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-3-2": {
		id: "ARCANA-3-2",
		title: "Flight",
		description:
			"Mark a *Stress* to take flight for a number of minutes equal to your level. While flying, you may spend a *Hope* to pick up and carry another creature approximately your size or smaller. You cannot carry more than one other creature at a time.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-2-2": {
		id: "ARCANA-2-2",
		title: "Floating Eye",
		description:
			"You can spend a *Hope* to create a single, small floating orb that you can control anywhere within very far range from you. While controlling it, you can choose to see through its vision as though it's your own. If the orb takes damage or moves out of range, the spell will immediately end.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-5-2": {
		id: "ARCANA-5-2",
		title: "Premonition",
		description:
			"You can channel the arcane energy to have visions of the future. Once per long rest, immediately after the GM conveys the consequences of you rolling with *Fear*, you may make that event your Premonition. You instead rescind the action and consequences like they never happened and choose another action instead.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-4-2": {
		id: "ARCANA-4-2",
		title: "Preservation Blast",
		description:
			"Make a *Spellcast Roll* against all enemies within melee range of you. Any you succeed against are hurdled into far range and dealt *d8* magic damage using your Spellcast Trait.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-6-1": {
		id: "ARCANA-6-1",
		title: "Rift Walker",
		description:
			"Once per long rest, on a successful *Spellcast Roll (15)* you place an arcane marking upon the ground where you currently stand. The next time you successfully cast *Rift Walker* with a *Spellcast Roll (15)*, a rift in space will open up, providing safe passage back to the exact spot where the marking was placed. You may drop the marking at anytime to cast *Rift Walker* again and place it somewhere new.\nThis rift stays open until you choose to close it or you cast another spell.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-1": {
		id: "ARCANA-1-1",
		title: "Rune Ward",
		description:
			"You have a deeply personal token or trinket that can be infused with protective magic and held as a ward by you or an ally. Describe what it is and why it's important to you. When the holder of the ward takes damage, they can *spend Hope* to reduce it by *1d8*.\nIf the ward die rolls an *8*, its power will temporarily end after it reduces damage this turn. It can be recharged for free on your next rest.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-9-2": {
		id: "ARCANA-9-2",
		title: "Sensory Projection",
		description:
			"Once per short rest, make a *Spellcast Roll (15)*. On a success, drop into a vision that lets you clearly see and hear any place you have been before in this moment as though you are standing there. You can move freely in this vision and are not constrained by the physics or impediments of a physical body. This spell cannot be detected by mundane or magical means and you will drop out of this vision immediately upon taking damage or casting another spell.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-6-2": {
		id: "ARCANA-6-2",
		title: "Telekinesis",
		description:
			"Make a *Spellcast Roll* against an object or target within far range. On a success, you can move it anywhere within far range of its current position using only your mind. If the target is unwilling, you must spend *1* or more *Stress* to do so, and can deal *1d20* magic damage per *Stress* spent. If you are hitting a creature with the target, divide the damage equally between the two.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-2": {
		id: "ARCANA-1-2",
		title: "Unleash Chaos",
		description:
			"At the beginning of a session, place a number of tokens equal to your Spellcast Trait on this card.\nYou can make a *Spellcast Roll* against a target within far range and spend any number of tokens to channel raw energy from within yourself and unleash against them. On a success, roll a number of *d10* equal to the tokens you spent, and do that much magic damage to the target. Mark a *Stress* to replenish this card with tokens, up to your *Spellcast Trait*. Clear all tokens at the end of the session.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-1-3": {
		id: "ARCANA-1-3",
		title: "Wall Walk",
		description:
			"Spend a *Hope* to allow a creature you can touch to climb on walls and ceilings as easily as walking on the ground below. This spell will end after ten minutes or when you cast it on another creature.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-1": {
		id: "BLADE-1-1",
		title: "Not Good Enough",
		description:
			"When you roll your damage dice, you may reroll any *1s* or *2s*. If you do, you must take the new result, even on a *1* or *2*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-2": {
		id: "BLADE-1-2",
		title: "Retaliation",
		description:
			"When you take damage from a creature in melee range, you may mark a *Stress* to immediately deal weapon damage to the creature at half *Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-3": {
		id: "BLADE-1-3",
		title: "Whirlwind",
		description:
			"When you make a successful attack using a weapon with melee or very close range, you may also spend a *Hope* to use that roll against every other enemy in that weapon's range. Any additional enemies you succeed against with this ability take half damage (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-2-1": {
		id: "BLADE-2-1",
		title: "A Soldier's Bond",
		description:
			"Once per long rest, if you compliment someone or ask them about something they are good at, you may both take *3 Hope*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-2-2": {
		id: "BLADE-2-2",
		title: "Reckless",
		description:
			"You may always mark a *Stress* to take <i>advantage</i> on an *Attack Roll* against a target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-3-1": {
		id: "BLADE-3-1",
		title: "Scramble",
		description:
			"Once per short rest, when an enemy in melee range would deal damage to you, you can avoid the damage entirely and safely move out of melee range of the enemy.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-3-2": {
		id: "BLADE-3-2",
		title: "Versatile Fighter",
		description:
			"You can choose to use the Character Trait of your choice on an equipped weapon, rather than the trait the weapon calls for.\nWhen dealing damage, you may mark a *Stress* to take the maximum value of one of your *Damage Die* instead of rolling it.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-4-1": {
		id: "BLADE-4-1",
		title: "Deadly Focus",
		description:
			"Once per short rest, you can apply all your focus towards a single target. Choose that target. Until you attack another target, you defeat the creature, or the battle ends, add *+1* to your *Proficiency*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-4-2": {
		id: "BLADE-4-2",
		title: "Fortified Armor",
		description:
			"Increase your *Armor Score* by *+2* while you are wearing armor and this card is in your loadout. Once per short rest, you may use an Armor Slot without marking it.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-5-1": {
		id: "BLADE-5-1",
		title: "Hero's Strike",
		description:
			"When you land a critical hit on an *Attack Roll*, choose two of the following:<ul><li>Clear a Hit Point.</li><li>Clear a marked Armor Slot.</li><li>Mark +1 Hit Point on the target of the attack.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-5-2": {
		id: "BLADE-5-2",
		title: "Prowess",
		description:
			"*When you take this card, choose two:*<ul><li>Permanently add one additional *Stress* slot</li><li>Permanently add one additional *Hit Point Slot*</li><li>Permanently raise your *Minor Damage Threshold to 5*. Any damage that comes in below this value does not mark any hit points.</li></ul>\nThen place it into your Vault *permanently.*",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-6-1": {
		id: "BLADE-6-1",
		title: "Battle Hardened",
		description:
			"Once per long rest, when you mark your final Hit Point, instead of making a death move, you can choose to automatically take a *Scar* (permanently cross out one *Hope Slot*), and roll *1d6*. Clear that many Hit Points and stay on your feet.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-6-2": {
		id: "BLADE-6-2",
		title: "Rage Up",
		description:
			"Before making an *Attack Roll*, you may mark a *Stress* to temporarily increase your Proficiency by *+1* until the end of the attack.\nYou may Rage Up twice per *Attack Roll*.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-7-1": {
		id: "BLADE-7-1",
		title: "Battle Touched",
		description:
			"When a majority of the domain cards in your *loadout* are from the *Blade* domain:<ul><li>*Attack Rolls always* take *+2* to their result.</li><li>Increase your *Severe Damage Threshold* by *+4*.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-7-2": {
		id: "BLADE-7-2",
		title: "Glancing Blow",
		description:
			"Whenever you make an attack that misses its target, you may mark a *Stress* to still hit the target for weapon damage at half Proficiency (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-8-1": {
		id: "BLADE-8-1",
		title: "Battle Cry",
		description:
			"Once per short rest, while you are charging into danger, you can muster a rousing shout or phrase that inspires your allies. You and all your allies that can hear you each clear a *Stress*, gain a *Hope*, and until you or an ally fails a roll with *Fear*, gain *+1* Proficiency.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-8-2": {
		id: "BLADE-8-2",
		title: "Frenzy",
		description:
			"Once per long rest, you can go into a *frenzied state* until there are no more threats within sight.\nWhile *frenzied*, you cannot use *Armor Slots*, you have *+2* to your *Proficiency*, and your *Severe Damage Threshold* is increased by *+8*.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-9-1": {
		id: "BLADE-9-1",
		title: "Gore and Glory",
		description:
			"Whenever you deal enough Weapon damage to defeat an enemy, you can gain a *Hope* or clear a *Stress*. When you roll a Critical Success on a weapon attack, you gain an additional *Hope* or clear an additional *Stress*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-9-2": {
		id: "BLADE-9-2",
		title: "Reaper Strike",
		description:
			"You may declare you are using *Reaper Strike*. Spend a *Hope* and make an *Attack Roll*. The GM will tell you any enemy it would succeed against in range of your weapon. Once per long rest, choose one of these enemies, and immediately deal *5 Hit Points* of damage to them.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-10-1": {
		id: "BLADE-10-1",
		title: "Battle Monster",
		description:
			"When you make a successful attack against an enemy, instead of rolling for damage you may spend *6 Hope* to deal the target a number of *Hit Points* equal to the amount of *Hit Points* you currently have marked.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BLADE-10-2": {
		id: "BLADE-10-2",
		title: "Onslaught",
		description:
			"When you successfully hit, your weapon attacks never deal damage beneath a target's *Major Damage Threshold* (you will always deal a minimum of *2 Hit Points* of damage).\nIn addition, whenever an enemy within weapon range deals damage to an ally with an attack that doesn't include you, you can mark a *Stress* to immediately deal weapon damage to the enemy at *half Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BONE-1-1": {
		id: "BONE-1-1",
		title: "Deft Maneuvers",
		description:
			"You can mark a *Stress* to move anywhere within far range without making an *Agility Roll* to get there.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-2": {
		id: "BONE-1-2",
		title: "I see it coming",
		description:
			"When you are targeted by a ranged attack, mark a *Stress* to roll a *d6* and increase your *Evasion* against this attack by its value.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-3": {
		id: "BONE-1-3",
		title: "Nimble",
		description:
			"While this card is in your loadout, add half of your Agility score to your Evasion (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-2-1": {
		id: "BONE-2-1",
		title: "Ferocity",
		description:
			"When you cause an enemy to mark any Hit Points, spend a *Hope* to temporarily increase your *Evasion* by the number of *Hit Points* you dealt. This bonus lasts until after the next attack that targets you.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
	"BONE-2-2": {
		id: "BONE-2-2",
		title: "Strategic Approach",
		description:
			"After a long rest, place a number of tokens equal to your Knowledge Trait on this card, with a minimum of *1*. When you move into melee range of an enemy and make an *Attack Roll* against them, you may spend one token to choose an option below.<ul><li>Make the attack at advantage.</li><li>Don't add a character token to the action tracker for this attack.</li><li>Add 1d8 to your damage.</li></ul>\n\nWhen you take a long rest, clear all unused tokens.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
	"BONE-3-1": {
		id: "BONE-3-1",
		title: "Brace",
		description:
			"When you use an Armor Slot to reduce incoming damage, you may also spend any number of *Hope*. For every *Hope* you spend, reduce the incoming damage by the value of your *Proficiency*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
	"BONE-3-2": {
		id: "BONE-3-2",
		title: "Tactician",
		description:
			"When you *Help* an *Ally*, they can add one of your *Experience* to their roll as well. When making a *Tag Team* roll, you can roll a *d20* for your *Hope* die instead of a *d12*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
	"BONE-4-1": {
		id: "BONE-4-1",
		title: "Boost",
		description:
			"If you have an ally in close range of you, mark a *Stress* to boost off of them and into the air to perform an aerial attack at an enemy within far range. You have advantage on the attack, add *1d10* to the damage, and end your action in melee range of the target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
	"BONE-4-2": {
		id: "BONE-4-2",
		title: "Redirect",
		description:
			"When you successfully evade a ranged attack, you may roll a number of *d6* equal to your proficiency. If any roll a *6*, mark a *Stress* to redirect the attack to instead damage an enemy within very close range of you.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
	"BONE-5-1": {
		id: "BONE-5-1",
		title: "Know thy Enemy",
		description:
			"When observing a creature, you can make a *Instinct Roll* against the target. On a success, spend a *Hope* and ask the GM for two of the mechanical specifics about the target from below:<ul><li>Current Hit Points and unmarked stress.</li><li>Difficulty and Damage Thresholds.</li><li>Their Tactics and standard attack Damage Dice.</li><li>Their Moves and Experiences.</li></ul>\nOn a success, you may also mark a *Stress* to remove one *Fear* from the GM's *Fear Pool*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
	"BONE-5-2": {
		id: "BONE-5-2",
		title: "Signature Move",
		description:
			"You take on a signature move in battle that you can perform once per short rest. Name it and describe it. When you include its description in an action you're taking, use a *d20* instead of a *d12* as your *Hope* die. If the attack succeeds, you may clear a *Stress*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
	"BONE-6-1": {
		id: "BONE-6-1",
		title: "Rapid Riposte",
		description:
			"When you successfully evade an attack from melee range, you can mark a *Stress* to automatically deal damage from an active weapon to the attacker.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Bone,
		level: 6,
		isHomebrew: false,
	},
	"BONE-6-2": {
		id: "BONE-6-2",
		title: "Recovery",
		description:
			"During a short rest, you can always choose to do one of the long rest options instead. You may spend a *Hope* to let one additional party member do the same.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 6,
		isHomebrew: false,
	},
	"BONE-7-1": {
		id: "BONE-7-1",
		title: "Bone Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Bone domain:<ul><li>Increase your Agility by +1.</li><li>Before an attack roll targeting you, you can mark an Armor Slot to increase your evasion against it by half your Armor Score (rounded up).</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Bone,
		level: 7,
		isHomebrew: false,
	},
	"BONE-7-2": {
		id: "BONE-7-2",
		title: "Cruel Precision",
		description:
			"Whenever you make a successful attack with a weapon, add either your *Finesse* or *Agility* trait to the damage.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 7,
		isHomebrew: false,
	},
	"BONE-8-1": {
		id: "BONE-8-1",
		title: "Breaking Blow",
		description:
			"When you make a successful attack, you may mark a *Stress* to make the next successful attack against that same target do an additional *2d12* damage.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 8,
		isHomebrew: false,
	},
	"BONE-8-2": {
		id: "BONE-8-2",
		title: "Wrangle",
		description:
			"Make an *Agility Roll* against all enemies close to you. You may spend a *Hope* to move any enemies you are successful against to any position within close range.\n\nUse of this ability does not contribute a character token to the action tracker.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 8,
		isHomebrew: false,
	},
	"BONE-9-1": {
		id: "BONE-9-1",
		title: "On the Brink",
		description:
			"When you have one Hit Point remaining, always add your proficiency to your Evasion.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 9,
		isHomebrew: false,
	},
	"BONE-9-2": {
		id: "BONE-9-2",
		title: "Splintering Strike",
		description:
			"Make an *Attack Roll* against all enemies in your weapon’s range. On a success against any targets, once per long rest, you may roll a number of weapon damage dice equal to double your *Proficiency* plus your *Finesse Trait*. You can distribute this damage however you wish between any enemies you are successful against.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 9,
		isHomebrew: false,
	},
	"BONE-10-1": {
		id: "BONE-10-1",
		title: "Deathrun",
		description:
			"Spend *3 Hope* to run an open path through the battlefield and make an *Attack Roll* against all enemies within weapon range along your path. Of your successful targets, choose the order in which you deal damage. For the first, roll your weapon damage at *+1 Proficiency*. Then, remove one die from your pool and deal the remaining damage to the next target in descending order until you're out of damage dice or enemies.\n\nYou cannot target the same creature more than once.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 10,
		isHomebrew: false,
	},
	"BONE-10-2": {
		id: "BONE-10-2",
		title: "Unflappable",
		description:
			"After you successfully evade an attack, you may clear a *Stress*. If you successfully evade an attack and have no *Stress* to clear, instead gain a *Hope*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 10,
		isHomebrew: false,
	},
	"CODEX-1-1": {
		id: "CODEX-1-1",
		title: "Book of Ava",
		description:
			"*<i>Power Push</i>*: Make a *Spellcast Roll* against a target in melee range. On a success, they are blasted back to far range and take *d10* magic damage using your proficiency.\n*<i>Tava's Armor</i>*: Use an action to spend a *Hope* that gives a target you can touch *+1d6* to their Armor score the next time they mark an *Armor Slot*. You can't stack Tava's Armor on one creature.\n*<i>Ice Spikes</i>*: Make a *Spellcast Roll* to summon large ice spikes within very far range. If you use them as a weapon, on a success, deal *d6* physical damage using your proficiency.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
	"CODEX-1-2": {
		id: "CODEX-1-2",
		title: "Book of Illiat",
		description:
			"<i>*Slumber*</i>: Make a *Spellcast Roll* against a very close target. On a success, they fall into a deep sleep until they take damage or the GM spends a *Fear* to awaken them.\n<i>*Arcane Barrage*</i>: Once per short rest, use an action to spend any number of *Hope* and shoot magical projectiles that automatically strike an enemy within close range. Roll an amount of *d6* equal to the *Hope* you spent, and deal that much direct magic damage.\n<i>*Telepathy*</i>: You may open a line of mental communication with one target you can see. This connection lasts until you use this spell to connect with another creature.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
	"CODEX-1-3": {
		id: "CODEX-1-3",
		title: "Book of Tyfar",
		description:
			"<i>*Wild Flame*</i>: Make a *Spellcast Roll* against up to three enemies in melee range of you. A flame erupts from your hand, dealing *2d6* magic damage and a *Stress* to any you succeed against.\n<i>*Magic Hand*</i>: You can reach out with a magical hand the same size and strength as your own to anywhere within far range of you.\n<i>*Mysterious Mist*</i>: Use an action to spend a *Hope* and cast a temporary, thick fog that encircles a stationary area up to very close range your current location. Everyone within is Hidden to anybody outside the fog.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
  "CODEX-2-1": {
		id: "CODEX-2-1",
		title: "Book of Sitil",
		description:
			"*Adjust Appearance*: You can magically shift your appearance and clothing to avoid recognition.\n*Parallela*: Spend a *Hope* to cast this spell on yourself or one ally close to you. The next time that creature makes an attack, they can split the damage between any targets in range that the attack roll succeeds against.\n*Illusion*: Make a *Spellcast Roll (14)*. On a success, create a temporary visual illusion no larger than you within close range that will last for as long as you look at it. It holds up to scrutiny until an observer is within melee range.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 2,
		isHomebrew: false,
	},
	"CODEX-2-2": {
		id: "CODEX-2-2",
		title: "Book of Vagras",
		description:
			"*Runic Lock*: You can infuse a rune upon an object you are touching that can close (a lock, chest, box, bag, etc). It will lock the object from being opened by anyone besides those you choose. The spell can be broken by somebody with magic and an hour of time to study it.\n*Arcane Door*: When you have no enemies in melee range, make a *Spellcast Roll (13)*. On a success, spend a *Hope* to disappear from where you are and reappear somewhere within far range you can see.\n*Reveal*: Make a *Spellcast Roll*. If there is anything hidden within close range the roll would succeed against, it is no longer hidden.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 2,
		isHomebrew: false,
	},
  "CODEX-3-1": {
		id: "CODEX-3-1",
		title: "Book of Korvax",
		description:
			"*Levitation*: Make a *Spellcast Roll* to temporarily lift and move a target you can see up into the air within close range of where it currently is.\n*Recant*: Use an action to spend a *Hope* and make a target roll a *Reaction Roll (15)*. On a failure, they forget the last minute of your conversation.\n*Rune Circle*: Use an action to mark a *Stress* and create a temporary magical circle on the ground around you. Any creatures in melee range of this circle, or who enter melee range of this circle, take *2d12* magic damage and are pushed out at the end of their action.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 3,
		isHomebrew: false,
	},
	"CODEX-3-2": {
		id: "CODEX-3-2",
		title: "Book of Norai",
		description:
			"*Mystic Tether*: Make a *Spellcast Roll* against a target within far range. On a success, they are temporarily restrained and mark a *Stress*. If you target a flying creature, this brings them to the ground before restraining them.\n*Fireball*: Make a *Spellcast Roll* against a target within very far range. On a success, you throw a sphere of fire towards them that explodes upon impact. The target and all creatures very close to them must make a *Reaction Roll (12)*. On a failure, they take *d8* magic damage using your proficiency. On a success, they take half damage (rounded up).",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 3,
		isHomebrew: false,
	},
  "CODEX-4-1": {
		id: "CODEX-4-1",
		title: "Book of Exota",
		description:
			"*Counterspell*: Once per short rest, you can interrupt a spell or magical effect that is taking place to make a *Reaction Roll* using your *Spellcast* trait. On a success, the spell or effect is immediately stopped and any consequences are avoided.\n*Create Construct*: Spend a *Hope* to choose a group of objects around you and create an animated construct from them that obeys basic commands. Use a *Spellcast Roll* to command it to take action. When necessary, it shares your Evasion and Traits and its attacks deal *2d10* physical damage. You can only hold one construct at a time.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 4,
		isHomebrew: false,
	},
	"CODEX-4-2": {
		id: "CODEX-4-2",
		title: "Book of Grynn",
		description:
			"*Arcane Deflection*: Once per long rest, spend a *Hope* to completely negate any incoming damage from a single attack on you or an ally very close to you.\n*Time Lock*: Target a non-living object within far range. That object stops in time and space exactly where it is for a number of minutes equal to your Level. If a creature tries to move it, make a *Spellcast Roll* against them to maintain this spell.\n*Wall of Flame*: Use an action to mark a *Stress* and create a temporary wall of magical flame between two points within far range. Anything that passes through it takes *4d10* magic damage.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 4,
		isHomebrew: false,
	},
  "CODEX-5-1": {
		id: "CODEX-5-1",
		title: "Manifest Wall",
		description:
			"*Spellcast Roll (15)*. On a success, once per short rest, spend a *Hope* to create a temporary magical wall at any angle up to *50 feet* high from one point, within far range of you, to another. Any creatures or objects in its path are shunted to one side. It will dissipate at the end of your next long rest, or when you use this spell again.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 5,
		isHomebrew: false,
	},
	"CODEX-5-2": {
		id: "CODEX-5-2",
		title: "Teleport",
		description:
			"Once per long rest, you have the ability to instantly teleport yourself and a number of others within close range up to your Level somewhere you're aware of. Choose one option below to gain additional modifiers, then make a *Spellcast Roll (16)*:<ul><li>If you know the place very well, take +5.</li><li>If you've visited the place frequently, take +3.</li><li>If you've visited the place infrequently, take +1.</li><li>If you've only been there once, no modifiers.</li><li>If you've never been there, take -4.</li></ul>On a success, you appear where you were intending to go. On a failure, you appear off course, with the range of failure signifying how far off course.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 5,
		isHomebrew: false,
	},
  "CODEX-6-1": {
		id: "CODEX-6-1",
		title: "Banish",
		description:
			"Choose a target creature within close range. You can temporarily banish them from this realm. Use an action to roll an amount of *d20*s equal to your Spellcast Trait and tell the GM the highest result. The GM must make a *Reaction Roll* with a target number of this result.\nOn a success, they mark a *Stress*. If they fail, once per short rest, they are banished. On any rolls the PCs make with *Fear*, the GM reduces the target number by one and makes another *Reaction Roll*. If it succeeds, the creature returns from banishment.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Codex,
		level: 6,
		isHomebrew: false,
	},
	"CODEX-6-2": {
		id: "CODEX-6-2",
		title: "Sigil of Retribution",
		description:
			"Use an action to give the GM a *Fear* and mark a close enemy with a Sigil of Retribution. Every time that enemy does damage to you or your allies, put a *d8* on this card up to a maximum of your level. Any time you attack this enemy, you may choose to roll these dice and add their value to your total damage. This spell ends when you cast this spell on another creature.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 6,
		isHomebrew: false,
	},
  "CODEX-7-1": {
		id: "CODEX-7-1",
		title: "Book of Homet",
		description:
			"*Pass Through*: Make a *Spellcast Roll (13)* on a wall or door within close range. On a success, once per short rest, you and anyone who is touching you can pass through it. The spell drops once everyone is on the other side.\n*Plane Gate*: Make a *Spellcast Roll (14)*. On a success, once per long rest, you open a gateway to a location in another dimension or plane of existence that you are aware of. This gateway lasts for *1* minute, or until you wish it to close.",
		type: CardType.Grimoire,
		recall: 0,
		domain: Domain.Codex,
		level: 7,
		isHomebrew: false,
	},
	"CODEX-7-2": {
		id: "CODEX-7-2",
		title: "Codex Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Codex domain:<ul><li>You can always mark a Stress to add your proficiency to a spellcast roll.</li><li>Once per short rest, you may replace this card with any card from your Vault instead without paying a Recall cost.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Codex,
		level: 7,
		isHomebrew: false,
	},
  "CODEX-8-1": {
		id: "CODEX-8-1",
		title: "Book of Vyola",
		description:
			"*Memory Delve*: Make a *Spellcast Roll* against a target within far range. On a success, you get into the mind of the creature and ask a question. The GM will describe any memories they have that pertain to the answer.\n*Shared Clarity*: Once per long rest, spend *Hope* to choose two willing creatures. Whenever one of them should mark *Stress*, they can choose between the two of them who marks it. This spell will automatically end at their next rest.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 8,
		isHomebrew: false,
	},
	"CODEX-8-2": {
		id: "CODEX-8-2",
		title: "Haven",
		description:
			"When you have a few minutes of calm to focus, you may spend *2 Hope* to summon your Haven, a large interdimensional home for you and your allies to take shelter in. When you do, a magical door appears somewhere within close distance of you and is only enterable by those you choose. Once inside, you can make the entrance invisible. You and anyone else inside can always exit. Once you leave, the doorway must be summoned again.\nWhen you take a rest within your own Haven, you can take an additional *Downtime Action*.",
		type: CardType.Spell,
		recall: 3,
		domain: Domain.Codex,
		level: 8,
		isHomebrew: false,
	},
  "CODEX-9-1": {
		id: "CODEX-9-1",
		title: "Book of Ronin",
		description:
			"*Transform*: Make a *Spellcast Roll (15)*. On a success, immediately transform into the shape of an inanimate object you can picture in your mind no larger than twice your normal size. You can remain in this shape until you take Hit Point damage. You can move in this form, but it might draw attention.\n*Stable Portal*: Once per long rest, use an action to mark a *Stress* and choose two points within very far distance of you. A temporary portal will open up at both of those points, and any creature may use this portal to move between these two points freely. The spell will end at your next short rest.",
		type: CardType.Grimoire,
		recall: 4,
		domain: Domain.Codex,
		level: 9,
		isHomebrew: false,
	},
	"CODEX-9-2": {
		id: "CODEX-9-2",
		title: "Disintegration Wave",
		description:
			"Make a *Spellcast Roll (14)*. On a success, once per long rest, the GM will tell you what enemies within far range have a difficulty of 14 or lower. You may mark a Stress for each one you wish to hit with this spell. They are immediately killed and cannot come back to life by any means.",
		type: CardType.Spell,
		recall: 4,
		domain: Domain.Codex,
		level: 9,
		isHomebrew: false,
	},
  "CODEX-10-1": {
		id: "CODEX-10-1",
		title: "Book of Yarrow",
		description:
			"*Timejammer*: Make a *Spellcast Roll (18)*. On a success, time temporarily slows to a halt for everyone within far range except for you. It automatically resumes the next time you make an action roll that targets another creature or after a number of minutes equal to your *Knowledge Trait*.\n*Magic Immunity*: Spend *5 Hope* to become immune to magic damage until your next short rest.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 10,
		isHomebrew: false,
	},
	"CODEX-10-2": {
		id: "CODEX-10-2",
		title: "Transcendent Union",
		description:
			"Once per long rest, spend *5 Hope* to cast this spell on two or more willing creatures that wish to be bonded. Until your next short rest, any creatures that have this union with each other can always share Hit Points Slots and Stress Slots between them.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Codex,
		level: 10,
		isHomebrew: false,
	},
};
