import { CardType, Domain, SkillCard } from "../types";

export const SYSTEM_SKILL_CARDS: Record<string, SkillCard> = {
	"ARCANA-10-1": {
		id: "ARCANA-10-1",
		title: "Adjust Reality",
		description:
			"After a dice roll you or a willing ally makes, you may spend <b>5 Hope</b> to change the results of that roll to a result of your choice instead. The result must be plausible within the range of the dice.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-7-1": {
		id: "ARCANA-7-1",
		title: "Arcana Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Arcana domain: \n<ul><li>Gain +1 to your Spellcast rolls.</li><li>Once per short rest, switch the values on your Hope and Fear die.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-1": {
		id: "ARCANA-8-1",
		title: "Arcane Reflection",
		description:
			"Whenever you would take magic damage, if you choose not to reduce it using <b>Armor</b>, you may spend a *Hope* to roll an amount of *d6* equal to your *Spellcast Trait*. If any of the dice roll a result of *6*, the attack is reflected back onto the caster, dealing the damage to them instead.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-4-1": {
		id: "ARCANA-4-1",
		title: "Blink Out",
		description:
			"Make a *Spellcast Roll (12)*. On a success, spend a *Hope* and vanish, teleporting to another place you can see within very far range. If any creatures are very close to you when you succeed, you can spend an additional *Hope* each to bring them with you.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-5-1": {
		id: "ARCANA-5-1",
		title: "Chain Lightning",
		description:
			"Once per short rest, make a *Spellcast Roll* against every adversary in front of you within close range. On a success, the GM must make a *Reaction Roll (16)* for the targets. On a failure, they take *3d8* plus a number of *d8*s equal to your *Spellcast Trait* in magic damage. On a success, they take half damage (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-2-1": {
		id: "ARCANA-2-1",
		title: "Cinder Grasp",
		description:
			"Make a *Spellcast Roll* against a target in melee range. On a success, the target instantly bursts into flames, dealing *1d20* magic damage and temporarily catching them on fire.\nAny time a creature tries to act while on fire, it must take an additional *2d6* magic damage if it is still on fire at the end of its action.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-7-2": {
		id: "ARCANA-7-2",
		title: "Cloaking Blast",
		description:
			"Make an *Attack Roll* using your primary weapon against a target. On a success, along with dealing damage, you can also spend a *Hope* to immediately become hidden.\nHidden only drops the next time you make an action roll or the GM uses all of the tokens on the action tracker.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 7,
		isHomebrew: false,
	},
	"ARCANA-8-2": {
		id: "ARCANA-8-2",
		title: "Confusing Aura",
		description:
			"Make a *Spellcast Roll (14)*. Once per *long rest*, on a success you create a layer of illusion over your body that makes it hard to tell exactly where you are. You may mark any number of *stress* to make that many additional layers. When an adversary makes an attack against you, roll a number of *d6* equal to the number of layers currently active. If any land on a *4+*, one layer of the aura is destroyed and you avoid the attack. If all are *3-*, you take the damage and the effect ends.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 8,
		isHomebrew: false,
	},
	"ARCANA-3-1": {
		id: "ARCANA-3-1",
		title: "Counterspell",
		description:
			"You can interrupt a spell or magical effect that is taking place to make a *Reaction Roll* using your *Spellcast* trait. On a success, the spell or effect is immediately stopped and any consequences are avoided, and this card is placed into your *Vault*.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-9-1": {
		id: "ARCANA-9-1",
		title: "Earthquake",
		description:
			"Make a *Spellcast Roll (16)*. Once per *short rest*, on a success all creatures within *very far range* of your choice must make a *Reaction Roll (18)*. On a failure, they take *3d10* <i>physical damage</i> and are *Vulnerable*. On a success, they take half damage (rounded up).\n\nWhen you successfully cast this spell, all terrain within *very far range* of you becomes *difficult* to move through, and structures within this range may sustain damage or crumble.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-10-2": {
		id: "ARCANA-10-2",
		title: "Falling Sky",
		description:
			"Make a *Spellcast Roll* against all enemies within far range. Mark any number of *Stress* to make shards of arcana rain down from above, dealing *1d20* damage per each *Stress* you marked to any targets you succeed against.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 10,
		isHomebrew: false,
	},
	"ARCANA-3-2": {
		id: "ARCANA-3-2",
		title: "Flight",
		description:
			"Mark a *Stress* to take flight for a number of minutes equal to your level. While flying, you may spend a *Hope* to pick up and carry another creature approximately your size or smaller. You cannot carry more than one other creature at a time.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 3,
		isHomebrew: false,
	},
	"ARCANA-2-2": {
		id: "ARCANA-2-2",
		title: "Floating Eye",
		description:
			"You can spend a *Hope* to create a single, small floating orb that you can control anywhere within very far range from you. While controlling it, you can choose to see through its vision as though it's your own. If the orb takes damage or moves out of range, the spell will immediately end.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Arcana,
		level: 2,
		isHomebrew: false,
	},
	"ARCANA-5-2": {
		id: "ARCANA-5-2",
		title: "Premonition",
		description:
			"You can channel the arcane energy to have visions of the future. Once per long rest, immediately after the GM conveys the consequences of you rolling with *Fear*, you may make that event your Premonition. You instead rescind the action and consequences like they never happened and choose another action instead.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 5,
		isHomebrew: false,
	},
	"ARCANA-4-2": {
		id: "ARCANA-4-2",
		title: "Preservation Blast",
		description:
			"Make a *Spellcast Roll* against all enemies within melee range of you. Any you succeed against are hurdled into far range and dealt *d8* magic damage using your Spellcast Trait.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 4,
		isHomebrew: false,
	},
	"ARCANA-6-1": {
		id: "ARCANA-6-1",
		title: "Rift Walker",
		description:
			"Once per long rest, on a successful *Spellcast Roll (15)* you place an arcane marking upon the ground where you currently stand. The next time you successfully cast *Rift Walker* with a *Spellcast Roll (15)*, a rift in space will open up, providing safe passage back to the exact spot where the marking was placed. You may drop the marking at anytime to cast *Rift Walker* again and place it somewhere new.\nThis rift stays open until you choose to close it or you cast another spell.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-1": {
		id: "ARCANA-1-1",
		title: "Rune Ward",
		description:
			"You have a deeply personal token or trinket that can be infused with protective magic and held as a ward by you or an ally. Describe what it is and why it's important to you. When the holder of the ward takes damage, they can *spend Hope* to reduce it by *1d8*.\nIf the ward die rolls an *8*, its power will temporarily end after it reduces damage this turn. It can be recharged for free on your next rest.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-9-2": {
		id: "ARCANA-9-2",
		title: "Sensory Projection",
		description:
			"Once per short rest, make a *Spellcast Roll (15)*. On a success, drop into a vision that lets you clearly see and hear any place you have been before in this moment as though you are standing there. You can move freely in this vision and are not constrained by the physics or impediments of a physical body. This spell cannot be detected by mundane or magical means and you will drop out of this vision immediately upon taking damage or casting another spell.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 9,
		isHomebrew: false,
	},
	"ARCANA-6-2": {
		id: "ARCANA-6-2",
		title: "Telekinesis",
		description:
			"Make a *Spellcast Roll* against an object or target within far range. On a success, you can move it anywhere within far range of its current position using only your mind. If the target is unwilling, you must spend *1* or more *Stress* to do so, and can deal *1d20* magic damage per *Stress* spent. If you are hitting a creature with the target, divide the damage equally between the two.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Arcana,
		level: 6,
		isHomebrew: false,
	},
	"ARCANA-1-2": {
		id: "ARCANA-1-2",
		title: "Unleash Chaos",
		description:
			"At the beginning of a session, place a number of tokens equal to your Spellcast Trait on this card.\nYou can make a *Spellcast Roll* against a target within far range and spend any number of tokens to channel raw energy from within yourself and unleash against them. On a success, roll a number of *d10* equal to the tokens you spent, and do that much magic damage to the target. Mark a *Stress* to replenish this card with tokens, up to your *Spellcast Trait*. Clear all tokens at the end of the session.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"ARCANA-1-3": {
		id: "ARCANA-1-3",
		title: "Wall Walk",
		description:
			"Spend a *Hope* to allow a creature you can touch to climb on walls and ceilings as easily as walking on the ground below. This spell will end after ten minutes or when you cast it on another creature.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Arcana,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-1": {
		id: "BLADE-1-1",
		title: "Not Good Enough",
		description:
			"When you roll your damage dice, you may reroll any *1s* or *2s*. If you do, you must take the new result, even on a *1* or *2*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-2": {
		id: "BLADE-1-2",
		title: "Retaliation",
		description:
			"When you take damage from a creature in melee range, you may mark a *Stress* to immediately deal weapon damage to the creature at half *Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-1-3": {
		id: "BLADE-1-3",
		title: "Whirlwind",
		description:
			"When you make a successful attack using a weapon with melee or very close range, you may also spend a *Hope* to use that roll against every other enemy in that weapon's range. Any additional enemies you succeed against with this ability take half damage (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 1,
		isHomebrew: false,
	},
	"BLADE-2-1": {
		id: "BLADE-2-1",
		title: "A Soldier's Bond",
		description:
			"Once per long rest, if you compliment someone or ask them about something they are good at, you may both take *3 Hope*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-2-2": {
		id: "BLADE-2-2",
		title: "Reckless",
		description:
			"You may always mark a *Stress* to take <i>advantage</i> on an *Attack Roll* against a target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 2,
		isHomebrew: false,
	},
	"BLADE-3-1": {
		id: "BLADE-3-1",
		title: "Scramble",
		description:
			"Once per short rest, when an enemy in melee range would deal damage to you, you can avoid the damage entirely and safely move out of melee range of the enemy.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-3-2": {
		id: "BLADE-3-2",
		title: "Versatile Fighter",
		description:
			"You can choose to use the Character Trait of your choice on an equipped weapon, rather than the trait the weapon calls for.\nWhen dealing damage, you may mark a *Stress* to take the maximum value of one of your *Damage Die* instead of rolling it.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 3,
		isHomebrew: false,
	},
	"BLADE-4-1": {
		id: "BLADE-4-1",
		title: "Deadly Focus",
		description:
			"Once per short rest, you can apply all your focus towards a single target. Choose that target. Until you attack another target, you defeat the creature, or the battle ends, add *+1* to your *Proficiency*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-4-2": {
		id: "BLADE-4-2",
		title: "Fortified Armor",
		description:
			"Increase your *Armor Score* by *+2* while you are wearing armor and this card is in your loadout. Once per short rest, you may use an Armor Slot without marking it.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 4,
		isHomebrew: false,
	},
	"BLADE-5-1": {
		id: "BLADE-5-1",
		title: "Hero's Strike",
		description:
			"When you land a critical hit on an *Attack Roll*, choose two of the following:<ul><li>Clear a Hit Point.</li><li>Clear a marked Armor Slot.</li><li>Mark +1 Hit Point on the target of the attack.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-5-2": {
		id: "BLADE-5-2",
		title: "Prowess",
		description:
			"*When you take this card, choose two:*<ul><li>Permanently add one additional *Stress* slot</li><li>Permanently add one additional *Hit Point Slot*</li><li>Permanently raise your *Minor Damage Threshold to 5*. Any damage that comes in below this value does not mark any hit points.</li></ul>\nThen place it into your Vault *permanently.*",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 5,
		isHomebrew: false,
	},
	"BLADE-6-1": {
		id: "BLADE-6-1",
		title: "Battle Hardened",
		description:
			"Once per long rest, when you mark your final Hit Point, instead of making a death move, you can choose to automatically take a *Scar* (permanently cross out one *Hope Slot*), and roll *1d6*. Clear that many Hit Points and stay on your feet.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-6-2": {
		id: "BLADE-6-2",
		title: "Rage Up",
		description:
			"Before making an *Attack Roll*, you may mark a *Stress* to temporarily increase your Proficiency by *+1* until the end of the attack.\nYou may Rage Up twice per *Attack Roll*.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 6,
		isHomebrew: false,
	},
	"BLADE-7-1": {
		id: "BLADE-7-1",
		title: "Battle Touched",
		description:
			"When a majority of the domain cards in your *loadout* are from the *Blade* domain:<ul><li>*Attack Rolls always* take *+2* to their result.</li><li>Increase your *Severe Damage Threshold* by *+4*.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-7-2": {
		id: "BLADE-7-2",
		title: "Glancing Blow",
		description:
			"Whenever you make an attack that misses its target, you may mark a *Stress* to still hit the target for weapon damage at half Proficiency (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Blade,
		level: 7,
		isHomebrew: false,
	},
	"BLADE-8-1": {
		id: "BLADE-8-1",
		title: "Battle Cry",
		description:
			"Once per short rest, while you are charging into danger, you can muster a rousing shout or phrase that inspires your allies. You and all your allies that can hear you each clear a *Stress*, gain a *Hope*, and until you or an ally fails a roll with *Fear*, gain *+1* Proficiency.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-8-2": {
		id: "BLADE-8-2",
		title: "Frenzy",
		description:
			"Once per long rest, you can go into a *frenzied state* until there are no more threats within sight.\nWhile *frenzied*, you cannot use *Armor Slots*, you have *+2* to your *Proficiency*, and your *Severe Damage Threshold* is increased by *+8*.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 8,
		isHomebrew: false,
	},
	"BLADE-9-1": {
		id: "BLADE-9-1",
		title: "Gore and Glory",
		description:
			"Whenever you deal enough Weapon damage to defeat an enemy, you can gain a *Hope* or clear a *Stress*. When you roll a Critical Success on a weapon attack, you gain an additional *Hope* or clear an additional *Stress*.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-9-2": {
		id: "BLADE-9-2",
		title: "Reaper Strike",
		description:
			"You may declare you are using *Reaper Strike*. Spend a *Hope* and make an *Attack Roll*. The GM will tell you any enemy it would succeed against in range of your weapon. Once per long rest, choose one of these enemies, and immediately deal *5 Hit Points* of damage to them.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Blade,
		level: 9,
		isHomebrew: false,
	},
	"BLADE-10-1": {
		id: "BLADE-10-1",
		title: "Battle Monster",
		description:
			"When you make a successful attack against an enemy, instead of rolling for damage you may spend *6 Hope* to deal the target a number of *Hit Points* equal to the amount of *Hit Points* you currently have marked.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BLADE-10-2": {
		id: "BLADE-10-2",
		title: "Onslaught",
		description:
			"When you successfully hit, your weapon attacks never deal damage beneath a target's *Major Damage Threshold* (you will always deal a minimum of *2 Hit Points* of damage).\nIn addition, whenever an enemy within weapon range deals damage to an ally with an attack that doesn't include you, you can mark a *Stress* to immediately deal weapon damage to the enemy at *half Proficiency* (rounded up).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Blade,
		level: 10,
		isHomebrew: false,
	},
	"BONE-1-1": {
		id: "BONE-1-1",
		title: "Deft Maneuvers",
		description:
			"You can mark a *Stress* to move anywhere within far range without making an *Agility Roll* to get there.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-2": {
		id: "BONE-1-2",
		title: "I see it coming",
		description:
			"When you are targeted by an attack coming from beyond *melee range*, mark a *Stress* to roll a *d4* and increase your *Evasion* against this attack by its value.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-1-3": {
		id: "BONE-1-3",
		title: "Nimble",
		description:
			"While this card is in your loadout, add half of your Agility score to your Evasion (rounded up).",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 1,
		isHomebrew: false,
	},
	"BONE-2-1": {
		id: "BONE-2-1",
		title: "Ferocity",
		description:
			"When you cause an enemy to mark any Hit Points, spend *2 Hope* to temporarily increase your *Evasion* by the number of *Hit Points* you dealt. This bonus lasts until after the next attack that targets you.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
	"BONE-2-2": {
		id: "BONE-2-2",
		title: "Strategic Approach",
		description:
			"After a long rest, place a number of tokens equal to your Knowledge Trait on this card, with a minimum of *1*. When you move into melee range of an enemy and make an *Attack Roll* against them, you may spend one token to choose an option below.<ul><li>Make the attack at advantage.</li><li>Don't add a character token to the action tracker for this attack.</li><li>Add 1d8 to your damage.</li></ul>\n\nWhen you take a long rest, clear all unused tokens.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 2,
		isHomebrew: false,
	},
	"BONE-3-1": {
		id: "BONE-3-1",
		title: "Brace",
		description:
			"When you use an Armor Slot to reduce incoming damage, you may also spend any number of *Hope*. For every *Hope* you spend, reduce the incoming damage by the value of your *Proficiency*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
	"BONE-3-2": {
		id: "BONE-3-2",
		title: "Tactician",
		description:
			"When you *Help* an *Ally*, they can add one of your *Experience* to their roll as well. When making a *Tag Team* roll, you can roll a *d20* for your *Hope* die instead of a *d12*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 3,
		isHomebrew: false,
	},
	"BONE-4-1": {
		id: "BONE-4-1",
		title: "Boost",
		description:
			"If you have an ally in close range of you, mark a *Stress* to boost off of them and into the air to perform an aerial attack at an enemy within far range. You have advantage on the attack, add *1d10* to the damage, and end your action in melee range of the target.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
	"BONE-4-2": {
		id: "BONE-4-2",
		title: "Redirect",
		description:
			"When you successfully evade an attack coming from beyond melee range, you may roll a number of *d6* equal to your proficiency. If any roll a *6*, mark a *Stress* to redirect the attack to instead damage an enemy within very close range of you.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 4,
		isHomebrew: false,
	},
	"BONE-5-1": {
		id: "BONE-5-1",
		title: "Know thy Enemy",
		description:
			"When observing a creature, you can make a *Instinct Roll* against the target. On a success, spend a *Hope* and ask the GM for two of the mechanical specifics about the target from below:<ul><li>Current Hit Points and unmarked stress.</li><li>Difficulty and Damage Thresholds.</li><li>Their Tactics and standard attack Damage Dice.</li><li>Their Moves and Experiences.</li></ul>\nOn a success, you may also mark a *Stress* to remove one *Fear* from the GM's *Fear Pool*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
	"BONE-5-2": {
		id: "BONE-5-2",
		title: "Signature Move",
		description:
			"You take on a signature move in battle that you can perform once per short rest. Name it and describe it. When you include its description in an action you're taking, use a *d20* instead of a *d12* as your *Hope* die. If the attack succeeds, you may clear a *Stress*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 5,
		isHomebrew: false,
	},
	"BONE-6-1": {
		id: "BONE-6-1",
		title: "Rapid Riposte",
		description:
			"When you successfully evade an attack from melee range, you can mark a *Stress* to automatically deal damage from an active weapon to the attacker.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Bone,
		level: 6,
		isHomebrew: false,
	},
	"BONE-6-2": {
		id: "BONE-6-2",
		title: "Recovery",
		description:
			"During a short rest, you can always choose to do one of the long rest options instead. You may spend a *Hope* to let one additional party member do the same.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 6,
		isHomebrew: false,
	},
	"BONE-7-1": {
		id: "BONE-7-1",
		title: "Bone Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Bone domain:<ul><li>Increase your Agility by *+1*.</li><li>Once per *short rest*, take an action in combat without adding a token to the action tracker</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Bone,
		level: 7,
		isHomebrew: false,
	},
	"BONE-7-2": {
		id: "BONE-7-2",
		title: "Cruel Precision",
		description:
			"Whenever you make a successful attack with a weapon, add either your *Finesse* or *Agility* trait to the damage.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 7,
		isHomebrew: false,
	},
	"BONE-8-1": {
		id: "BONE-8-1",
		title: "Breaking Blow",
		description:
			"When you make a successful attack, you may mark a *Stress* to make the next successful attack against that same target do an additional *2d12* damage.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 8,
		isHomebrew: false,
	},
	"BONE-8-2": {
		id: "BONE-8-2",
		title: "Wrangle",
		description:
			"Make an *Agility Roll* against all enemies close to you. You may spend a *Hope* to move any enemies you are successful against to any position within close range.\n\nUse of this ability does not contribute a character token to the action tracker.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 8,
		isHomebrew: false,
	},
	"BONE-9-1": {
		id: "BONE-9-1",
		title: "On the Brink",
		description:
			"When you have one Hit Point remaining, all of your damage thresholds are temporarily raised by *+5*",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 9,
		isHomebrew: false,
	},
	"BONE-9-2": {
		id: "BONE-9-2",
		title: "Splintering Strike",
		description:
			"Make an *Attack Roll* against all enemies in your weapon’s range. On a success against any targets, once per long rest, you may roll a number of weapon damage dice equal to double your *Proficiency* plus your *Finesse Trait*. You can distribute this damage however you wish between any enemies you are successful against.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Bone,
		level: 9,
		isHomebrew: false,
	},
	"BONE-10-1": {
		id: "BONE-10-1",
		title: "Deathrun",
		description:
			"Spend *3 Hope* to run an open path through the battlefield and make an *Attack Roll* against all enemies within weapon range along your path. Of your successful targets, choose the order in which you deal damage. For the first, roll your weapon damage at *+1 Proficiency*. Then, remove one die from your pool and deal the remaining damage to the next target in descending order until you're out of damage dice or enemies.\n\nYou cannot target the same creature more than once.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 10,
		isHomebrew: false,
	},
	"BONE-10-2": {
		id: "BONE-10-2",
		title: "Unflappable",
		description:
			"After you successfully evade an attack, you may clear a *Stress*. If you successfully evade an attack and have no *Stress* to clear, instead gain a *Hope*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Bone,
		level: 10,
		isHomebrew: false,
	},
	"CODEX-1-1": {
		id: "CODEX-1-1",
		title: "Book of Ava",
		description:
			"*<i>Power Push</i>*: Make a *Spellcast Roll* against a target in melee range. On a success, they are blasted back to far range and take *d10* magic damage using your proficiency.\n*<i>Tava's Armor</i>*: Use an action to spend a *Hope* that gives a target you can touch *+1d6* to their Armor score the next time they mark an *Armor Slot*. You can't stack Tava's Armor on one creature.\n*<i>Ice Spikes</i>*: Make a *Spellcast Roll* to summon large ice spikes within very far range. If you use them as a weapon, on a success, deal *d6* physical damage using your proficiency.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
	"CODEX-1-2": {
		id: "CODEX-1-2",
		title: "Book of Illiat",
		description:
			"<i>*Slumber*</i>: Make a *Spellcast Roll* against a very close target. On a success, they fall into a deep sleep until they take damage or the GM spends a *Fear* to awaken them.\n<i>*Arcane Barrage*</i>: Once per short rest, use an action to spend any number of *Hope* and shoot magical projectiles that automatically strike an enemy within close range. Roll an amount of *d6* equal to the *Hope* you spent, and deal that much direct magic damage.\n<i>*Telepathy*</i>: You may open a line of mental communication with one target you can see. This connection lasts until you use this spell to connect with another creature.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
	"CODEX-1-3": {
		id: "CODEX-1-3",
		title: "Book of Tyfar",
		description:
			"<i>*Wild Flame*</i>: Make a *Spellcast Roll* against up to three enemies in melee range of you. A flame erupts from your hand, dealing *2d6* magic damage and a *Stress* to any you succeed against.\n<i>*Magic Hand*</i>: You can reach out with a magical hand the same size and strength as your own to anywhere within far range of you.\n<i>*Mysterious Mist*</i>: Use an action to spend a *Hope* and cast a temporary, thick fog that encircles a stationary area up to very close range your current location. Everyone within is Hidden to anybody outside the fog.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 1,
		isHomebrew: false,
	},
	"CODEX-2-1": {
		id: "CODEX-2-1",
		title: "Book of Sitil",
		description:
			"*Adjust Appearance*: You can magically shift your appearance and clothing to avoid recognition.\n*Parallela*: Spend a *Hope* to cast this spell on yourself or one ally close to you. The next time that creature makes an attack, they can split the damage between any targets in range that the attack roll succeeds against.\n*Illusion*: Make a *Spellcast Roll (14)*. On a success, create a temporary visual illusion no larger than you within close range that will last for as long as you look at it. It holds up to scrutiny until an observer is within melee range.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 2,
		isHomebrew: false,
	},
	"CODEX-2-2": {
		id: "CODEX-2-2",
		title: "Book of Vagras",
		description:
			"*Runic Lock*: You can infuse a rune upon an object you are touching that can close (a lock, chest, box, bag, etc). It will lock the object from being opened by anyone besides those you choose. The spell can be broken by somebody with magic and an hour of time to study it.\n*Arcane Door*: When you have no enemies in melee range, make a *Spellcast Roll (13)*. On a success, spend a *Hope* to disappear from where you are and reappear somewhere within far range you can see.\n*Reveal*: Make a *Spellcast Roll*. If there is anything hidden within close range the roll would succeed against, it is no longer hidden.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 2,
		isHomebrew: false,
	},
	"CODEX-3-1": {
		id: "CODEX-3-1",
		title: "Book of Korvax",
		description:
			"*Levitation*: Make a *Spellcast Roll* to temporarily lift and move a target you can see up into the air within close range of where it currently is.\n*Recant*: Use an action to spend a *Hope* and make a target roll a *Reaction Roll (15)*. On a failure, they forget the last minute of your conversation.\n*Rune Circle*: Use an action to mark a *Stress* and create a temporary magical circle on the ground around you. Any creatures in melee range of this circle, or who enter melee range of this circle, take *2d12* magic damage and are pushed out at the end of their action.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 3,
		isHomebrew: false,
	},
	"CODEX-3-2": {
		id: "CODEX-3-2",
		title: "Book of Norai",
		description:
			"*Mystic Tether*: Make a *Spellcast Roll* against a target within far range. On a success, they are temporarily restrained and mark a *Stress*. If you target a flying creature, this brings them to the ground before restraining them.\n*Fireball*: Make a *Spellcast Roll* against a target within very far range. On a success, you throw a sphere of fire towards them that explodes upon impact. The target and all creatures very close to them must make a *Reaction Roll (12)*. On a failure, they take *d8* magic damage using your proficiency. On a success, they take half damage (rounded up).",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 3,
		isHomebrew: false,
	},
	"CODEX-4-1": {
		id: "CODEX-4-1",
		title: "Book of Exota",
		description:
			"*Counterspell*: Once per short rest, you can interrupt a spell or magical effect that is taking place to make a *Reaction Roll* using your *Spellcast* trait. On a success, the spell or effect is immediately stopped and any consequences are avoided, and this card is placed into your Vault.\n*Create Construct*: Spend a *Hope* to choose a group of objects around you and create an animated construct from them that obeys basic commands. Use a *Spellcast Roll* to command it to take action. When necessary, it shares your Evasion and Traits and its attacks deal *2d10* physical damage. You can only hold one construct at a time and it faild apart when it is hit for any amount of damage.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 4,
		isHomebrew: false,
	},
	"CODEX-4-2": {
		id: "CODEX-4-2",
		title: "Book of Grynn",
		description:
			"*Arcane Deflection*: Once per long rest, spend a *Hope* to completely negate any incoming damage from a single attack on you or an ally very close to you.\n*Time Lock*: Target a non-living object within far range. That object stops in time and space exactly where it is for a number of minutes equal to your Level. If a creature tries to move it, make a *Spellcast Roll* against them to maintain this spell.\n*Wall of Flame*: Use an action to mark a *Stress* and create a temporary wall of magical flame between two points within far range. Anything that passes through it takes *4d10* magic damage.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 4,
		isHomebrew: false,
	},
	"CODEX-5-1": {
		id: "CODEX-5-1",
		title: "Manifest Wall",
		description:
			"*Spellcast Roll (15)*. On a success, once per short rest, spend a *Hope* to create a temporary magical wall at any angle up to *50 feet* high from one point, within far range of you, to another. Any creatures or objects in its path are shunted to one side. It will dissipate at the end of your next long rest, or when you use this spell again.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 5,
		isHomebrew: false,
	},
	"CODEX-5-2": {
		id: "CODEX-5-2",
		title: "Teleport",
		description:
			"Once per long rest, you have the ability to instantly teleport yourself and a number of others within close range up to your Level somewhere you're aware of. Choose one option below to gain additional modifiers, then make a *Spellcast Roll (16)*:<ul><li>If you know the place very well, take +5.</li><li>If you've visited the place frequently, take +3.</li><li>If you've visited the place infrequently, take +1.</li><li>If you've only been there once, no modifiers.</li><li>If you've never been there, take -4.</li></ul>On a success, you appear where you were intending to go. On a failure, you appear off course, with the range of failure signifying how far off course.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 5,
		isHomebrew: false,
	},
	"CODEX-6-1": {
		id: "CODEX-6-1",
		title: "Banish",
		description:
			"Choose a target creature within close range. You can temporarily banish them from this realm. Use an action to roll an amount of *d20*s equal to your Spellcast Trait and tell the GM the highest result. The GM must make a *Reaction Roll* with a target number of this result.\nOn a success, they mark a *Stress*. If they fail, once per short rest, they are banished. On any rolls the PCs make with *Fear*, the GM reduces the target number by one and makes another *Reaction Roll*. If it succeeds, the creature returns from banishment.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Codex,
		level: 6,
		isHomebrew: false,
	},
	"CODEX-6-2": {
		id: "CODEX-6-2",
		title: "Sigil of Retribution",
		description:
			"Use an action to give the GM a *Fear* and mark a close enemy with a Sigil of Retribution. Every time that enemy does damage to you or your allies, put a *d8* on this card up to a maximum of your level. Any time you attack this enemy, you may choose to roll these dice and add their value to your total damage. This spell ends when you cast this spell on another creature.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Codex,
		level: 6,
		isHomebrew: false,
	},
	"CODEX-7-1": {
		id: "CODEX-7-1",
		title: "Book of Homet",
		description:
			"*Pass Through*: Make a *Spellcast Roll (13)* on a wall or door within close range. On a success, once per short rest, you and anyone who is touching you can pass through it. The spell drops once everyone is on the other side.\n*Plane Gate*: Make a *Spellcast Roll (14)*. On a success, once per long rest, you open a gateway to a location in another dimension or plane of existence that you are aware of. This gateway lasts for *1* minute, or until you wish it to close.",
		type: CardType.Grimoire,
		recall: 0,
		domain: Domain.Codex,
		level: 7,
		isHomebrew: false,
	},
	"CODEX-7-2": {
		id: "CODEX-7-2",
		title: "Codex Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Codex domain:<ul><li>You can always mark a Stress to add your proficiency to a spellcast roll.</li><li>Once per short rest, you may replace this card with any card from your Vault instead without paying a Recall cost.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Codex,
		level: 7,
		isHomebrew: false,
	},
	"CODEX-8-1": {
		id: "CODEX-8-1",
		title: "Book of Vyola",
		description:
			"*Memory Delve*: Make a *Spellcast Roll* against a target within far range. On a success, you get into the mind of the creature and ask a question. The GM will describe any memories they have that pertain to the answer.\n*Shared Clarity*: Once per long rest, spend *Hope* to choose two willing creatures. Whenever one of them should mark *Stress*, they can choose between the two of them who marks it. This spell will automatically end at their next rest.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 8,
		isHomebrew: false,
	},
	"CODEX-8-2": {
		id: "CODEX-8-2",
		title: "Haven",
		description:
			"When you have a few minutes of calm to focus, you may spend *2 Hope* to summon your Haven, a large interdimensional home for you and your allies to take shelter in. When you do, a magical door appears somewhere within close distance of you and is only enterable by those you choose. Once inside, you can make the entrance invisible. You and anyone else inside can always exit. Once you leave, the doorway must be summoned again.\nWhen you take a rest within your own Haven, you can take an additional *Downtime Action*.",
		type: CardType.Spell,
		recall: 3,
		domain: Domain.Codex,
		level: 8,
		isHomebrew: false,
	},
	"CODEX-9-1": {
		id: "CODEX-9-1",
		title: "Book of Ronin",
		description:
			"*Transform*: Make a *Spellcast Roll (15)*. On a success, immediately transform into the shape of an inanimate object you can picture in your mind no larger than twice your normal size. You can remain in this shape until you take Hit Point damage. You can move in this form, but it might draw attention.\n*Stable Portal*: Once per long rest, use an action to mark a *Stress* and choose two points within very far distance of you. A temporary portal will open up at both of those points, and any creature may use this portal to move between these two points freely. The spell will end at your next short rest.",
		type: CardType.Grimoire,
		recall: 4,
		domain: Domain.Codex,
		level: 9,
		isHomebrew: false,
	},
	"CODEX-9-2": {
		id: "CODEX-9-2",
		title: "Disintegration Wave",
		description:
			"Make a *Spellcast Roll (14)*. On a success, once per long rest, the GM will tell you what enemies within far range have a difficulty of 14 or lower. You may mark a Stress for each one you wish to hit with this spell. They are immediately killed and cannot come back to life by any means.",
		type: CardType.Spell,
		recall: 4,
		domain: Domain.Codex,
		level: 9,
		isHomebrew: false,
	},
	"CODEX-10-1": {
		id: "CODEX-10-1",
		title: "Book of Yarrow",
		description:
			"*Timejammer*: Make a *Spellcast Roll (18)*. On a success, time temporarily slows to a halt for everyone within far range except for you. It automatically resumes the next time you make an action roll that targets another creature or after a number of minutes equal to your *Knowledge Trait*.\n*Magic Immunity*: Spend *5 Hope* to become immune to magic damage until your next short rest.",
		type: CardType.Grimoire,
		recall: 2,
		domain: Domain.Codex,
		level: 10,
		isHomebrew: false,
	},
	"CODEX-10-2": {
		id: "CODEX-10-2",
		title: "Transcendent Union",
		description:
			"Once per long rest, spend *5 Hope* to cast this spell on two or more willing creatures that wish to be bonded. Until your next short rest, any creatures that have this union with each other can always share Hit Points Slots and Stress Slots between them.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Codex,
		level: 10,
		isHomebrew: false,
	},
	"GRACE-1-1": {
		id: "GRACE-1-1",
		title: "Deft Deceiver",
		description:
			"Spend a *Hope* to take advantage on a roll you make to deceive or trick someone into believing a lie you tell them.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Grace,
		level: 1,
		isHomebrew: false,
	},
	"GRACE-1-2": {
		id: "GRACE-1-2",
		title: "Enrapture",
		description:
			"Make a *Spellcast Roll* against a close target.\nOn a success, you can temporarily keep their attention on you, narrowing their field of view and drowning out any sound but your voice. Once per short rest, you may also mark a *Stress* on a success to deal a *Stress* to the target.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Grace,
		level: 1,
		isHomebrew: false,
	},
	"GRACE-1-3": {
		id: "GRACE-1-3",
		title: "Inspirational Words",
		description:
			"You can imbue your speech with enhancing power. At the beginning of a session, place a number of tokens on this card equal to your Presence score. When you recite your words, spend a token and choose an option from the list below to grant to the ally you are speaking to. If the action tracker is active, place that token on it. At the end of a session, clear all tokens.<ul><li>Clear a Stress</li><li>Heal a Hit Point.</li><li>Gain a Hope.</li>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Grace,
		level: 1,
		isHomebrew: false,
	},
	"GRACE-2-1": {
		id: "GRACE-2-1",
		title: "Tell no Lies",
		description:
			"Make a *Spellcast Roll* against a target within very close range. On a success, they can't lie to you while they remain within close range, but they are not compelled to speak. If you ask them a question and they refuse to answer, they mark a *Stress* and the spell ends.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 2,
		isHomebrew: false,
	},
	"GRACE-2-2": {
		id: "GRACE-2-2",
		title: "Troublemaker",
		description:
			"When you taunt or provoke a target within far range, make a *Presence Roll* against them. On a success, roll a number of *d4*s equal to your proficiency. Take the highest value from those *d4*s and deal that much *Stress* to the target.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Grace,
		level: 2,
		isHomebrew: false,
	},
	"GRACE-3-1": {
		id: "GRACE-3-1",
		title: "Hypnotic Shimmer",
		description:
			"Make a *Spellcast Roll* against any enemies in front of you within close range. On a success, once per short rest, you create an illusion of flashing colors and lights that can temporarily Stun any enemies you succeed against, dealing them a *Stress* and leaving them unable to move or act until *Stun* is cleared. While in combat, the GM can’t spend tokens from the action tracker to activate stunned creatures.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 3,
		isHomebrew: false,
	},
	"GRACE-3-2": {
		id: "GRACE-3-2",
		title: "Invisibility",
		description:
			"Make a *Spellcast Roll (10)* while touching a creature. On a success, mark a *Stress* and the target becomes hidden for *1* hour, until you cast this spell again, or until the target makes an *Attack* or *Spellcast Roll*.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 3,
		isHomebrew: false,
	},
	"GRACE-4-1": {
		id: "GRACE-4-1",
		title: "Soothing Speech",
		description:
			"During a short rest, when you use the Tend to Wounds downtime move on another character, you may speak supportive words to heal an extra Hit Point on them. When you do, also heal two of your own.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 4,
		isHomebrew: false,
	},
	"GRACE-4-2": {
		id: "GRACE-4-2",
		title: "Through Your Eyes",
		description:
			"Point to a target within very far range. You can now see through their eyes and hear through their ears. You may return to this vision at any time until you cast another spell or mark a Hit Point.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 4,
		isHomebrew: false,
	},
	"GRACE-5-1": {
		id: "GRACE-5-1",
		title: "Thought Delver",
		description:
			"You can peek into the minds of others. Spend a *Hope* to read the vague surface thoughts of a target within far range. Make a *Spellcast Roll* against the target to delve for deeper, more hidden thoughts.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Grace,
		level: 5,
		isHomebrew: false,
	},
	"GRACE-5-2": {
		id: "GRACE-5-2",
		title: "Words of Discord",
		description:
			"When you whisper words of discord to an adversary in melee range, make a *Spellcast Roll (13)*. On a success, the target immediately takes a *Stress* and makes an attack against another enemy instead of against you or your allies. If in combat, the GM spends a token from the action tracker to do so.\nOnce this attack is over, the target will realize what has happened. On the next use of Words of Discord against them, add *+5* to the *Spellcast Roll* difficulty.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 5,
		isHomebrew: false,
	},
	"GRACE-6-1": {
		id: "GRACE-6-1",
		title: "Never Upstaged",
		description:
			"When you mark one or more Hit Points from an attack, you may mark a *Stress* to place a number of tokens on this card equal to the number of Hit Points you marked. On your next attack, you may increase your Proficiency by *+1* for each token on this card, then clear all tokens.\nIf you have any tokens remaining on this card when you take a long rest, clear that much *Stress*.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Grace,
		level: 6,
		isHomebrew: false,
	},
	"GRACE-6-2": {
		id: "GRACE-6-2",
		title: "Share the Burden",
		description:
			"Once per short rest, you can use an action to absorb *Stress* from a willing creature you can touch. The target describes what intimate knowledge or emotions leak from their mind telepathically in this moment between you. Then, transfer any number of their marked Stress to you and you also gain a *Hope* for each *Stress* transferred.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Grace,
		level: 6,
		isHomebrew: false,
	},
	"GRACE-7-1": {
		id: "GRACE-7-1",
		title: "Endless Charisma",
		description:
			"Whenever you make an *Action Roll* to persuade, lie, or garner favor, you can spend a *Hope* to reroll the *Hope* or *Fear* die and take the new result instead.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Grace,
		level: 7,
		isHomebrew: false,
	},
	"GRACE-7-2": {
		id: "GRACE-7-2",
		title: "Grace Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Grace domain:<ul><li>You may mark an Armor Slot instead of marking *Stress*.</li><li>When you get a critical success on an Action Roll, an enemy within close range takes *2 Stress*, or an ally within close range gains *2 Hope*.</li><li>When you should mark a number of hit points on a target, you may choose instead to mark that many *Stress*/li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Grace,
		level: 7,
		isHomebrew: false,
	},
	"GRACE-8-1": {
		id: "GRACE-8-1",
		title: "Astral Projection",
		description:
			"Once per long rest, mark a *Stress* to create a projected copy of yourself that can appear anywhere you've been before.\nYou can see and hear through it as though it were you, and can affect the world as though you were there. Anyone investigating this projection can tell it's of magical origin. This spell ends at your next short rest or when your projection takes any damage.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Grace,
		level: 8,
		isHomebrew: false,
	},
	"GRACE-8-2": {
		id: "GRACE-8-2",
		title: "Mass Enrapture",
		description:
			"Make a *Spellcast Roll* against all enemies within far range. Any you succeed against temporarily keep their attention on you, narrowing their field of view and drowning out any sound but your own. You may also mark a *Stress* to deal *Stress* to all targets who are enraptured.",
		type: CardType.Spell,
		recall: 3,
		domain: Domain.Grace,
		level: 8,
		isHomebrew: false,
	},
	"GRACE-9-1": {
		id: "GRACE-9-1",
		title: "Copycat",
		description:
			"Once per long rest, this card can mimic the features of any other active Domain card in another player's loadout of Level *8* or lower. You must *spend Hope* equal to half the card's level (rounded up), and this lasts until your next short rest.",
		type: CardType.Spell,
		recall: 3,
		domain: Domain.Grace,
		level: 9,
		isHomebrew: false,
	},
	"GRACE-9-2": {
		id: "GRACE-9-2",
		title: "Master of the Craft",
		description:
			"Add *+2* to any two of your Experiences, or *+3* to any one of your Experiences. Then permanently put this card into your Vault.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Grace,
		level: 9,
		isHomebrew: false,
	},
	"GRACE-10-1": {
		id: "GRACE-10-1",
		title: "Encore",
		description:
			"When an ally within close distance of you deals damage to an enemy, you may make a *Spellcast Roll* against that same enemy. On a success, you immediately do the same amount of damage to them as your ally dealt. If your *Spellcast Roll* succeeds with *Fear*, place this card into your Vault afterward.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 10,
		isHomebrew: false,
	},
	"GRACE-10-2": {
		id: "GRACE-10-2",
		title: "Notorious",
		description:
			"People know who you are and what you've done, and will treat you differently because of it. Whenever you leverage your notoriety to get what you want, mark a *Stress* before you roll to take *+10* to the result. All food and drinks for you are always free wherever you go, and everything else you buy is reduced in price by one chest of gold (to a minimum of one handful).\nThis card must remain in your loadout, but doesn't count towards your domain card maximum.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Grace,
		level: 10,
		isHomebrew: false,
	},
	"MIDNIGHT-1-1": {
		id: "MIDNIGHT-1-1",
		title: "Pick and Pull",
		description:
			"You have advantage on any attempt to pick a non-magical lock, disarm a trap, or steal an item from a target (either through stealth or by force).",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Midnight,
		level: 1,
		isHomebrew: false,
	},
	"MIDNIGHT-1-2": {
		id: "MIDNIGHT-1-2",
		title: "Rain of Blades",
		description:
			"Spend *2 Hope* to conjure throwing blades that strike any enemies very close to you. Make a *Spellcast Roll* and all targets that you succeed against take *d8* magic damage using your proficiency.\nIf any targets you hit are currently Vulnerable, they take an additional *1d8* magic damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 1,
		isHomebrew: false,
	},
	"MIDNIGHT-1-3": {
		id: "MIDNIGHT-1-3",
		title: "Uncanny Disguise",
		description:
			"When you have a few minutes to prepare, you can mark a *Stress* to don the facade of any humanoid you can picture clearly in your mind. While disguised, all Presence rolls to avoid scrutiny have advantage. The spell will begin to fade after one hour.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Midnight,
		level: 1,
		isHomebrew: false,
	},
	"MIDNIGHT-2-1": {
		id: "MIDNIGHT-2-1",
		title: "Midnight Spirit",
		description:
			"Spend a *Hope* to summon an arcane spirit the same size as yourself that can move or carry things you can see until your next short rest.\nYou may also send it to make an attack on an enemy. When you do, make a *Spellcast Roll* against a target within very far range of you. On a success, roll an amount of *d6* equal to your Spellcast Trait and deal that much magic damage to the target. The spirit then dissipates.\nYou can only have one spirit at a time.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 2,
		isHomebrew: false,
	},
	"MIDNIGHT-2-2": {
		id: "MIDNIGHT-2-2",
		title: "Shadowbind",
		description:
			"Make a *Spellcast Roll* against all enemies within Very Close range. All it succeeds against have their shadows temporarily pinned where they are, making them <il>restrained</i>.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Midnight,
		level: 2,
		isHomebrew: false,
	},
	"MIDNIGHT-3-1": {
		id: "MIDNIGHT-3-1",
		title: "Chokehold",
		description:
			"While hidden, when you successfully position yourself behind a creature that's about your size, you can use an action to mark a *Stress* and pull them into a chokehold or equally compromising position, making them temporarily *Vulnerable*.\nEvery *Attack Roll* against them while they are *Vulnerable* from your chokehold adds *2d6* to the damage roll.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Midnight,
		level: 3,
		isHomebrew: false,
	},
	"MIDNIGHT-3-2": {
		id: "MIDNIGHT-3-2",
		title: "Veil of Shadows",
		description:
			"Make a *Spellcast Roll (13)*. On a success, you can create a temporary curtain of darkness from one point up to far range from you to another, as tall as twice your height. Only you can see through this darkness. Gain advantage on any attacks you make through the wall and you are considered hidden to any enemies on the other side. It will hold until you cast another spell.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 3,
		isHomebrew: false,
	},
	"MIDNIGHT-4-1": {
		id: "MIDNIGHT-4-1",
		title: "Stealth Expertise",
		description:
			"When you attempt to move through a dangerous area without being noticed, if you roll with *Fear*, you can always mark a *Stress* to change it to a roll with Hope instead.\nIf an ally within close range is also attempting to move without being noticed and rolls with *Fear*, you can mark a *Stress* to change their roll to a roll with *Hope* as well.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Midnight,
		level: 4,
		isHomebrew: false,
	},
	"MIDNIGHT-4-2": {
		id: "MIDNIGHT-4-2",
		title: "Twilight Mark",
		description:
			"Make a *Spellcast Roll* against a target within very close range. On a success, spend a Hope to conjure a dark glyph upon their body that exposes their weak points, temporarily reducing the target's *Difficulty* number by *1 + your Knowledge* trait.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 4,
		isHomebrew: false,
	},
	"MIDNIGHT-5-1": {
		id: "MIDNIGHT-5-1",
		title: "Hush",
		description:
			"Make a *Spellcast Roll* against a target within close range. On a success, spend a Hope to temporarily conjure suppressive magic around the target that encompasses everything within very close range of them and follows them as they move.\nThe target and anything within the area cannot make noise and cannot cast spells until the GM spends *2 Fear* to end it, you cast this spell again, or you take Major damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 5,
		isHomebrew: false,
	},
	"MIDNIGHT-5-2": {
		id: "MIDNIGHT-5-2",
		title: "Phantom Retreat",
		description:
			"Spend a *Hope* to activate Phantom Retreat where you're currently standing. You may spend another *Hope* at any time before your next short rest to disappear from where you are and reappear where you were standing when you activated Phantom Retreat. This will end the spell.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Midnight,
		level: 5,
		isHomebrew: false,
	},
	"MIDNIGHT-6-1": {
		id: "MIDNIGHT-6-1",
		title: "Dark Whispers",
		description:
			"You can speak into the mind of any person you've ever seen or know the true name of.\nWhen you do, you may also choose to mark a *Stress* to make a *Spellcast Roll* against them. On a success, you can ask one of the questions below.<ul><li>Where are they?</li><li>What are they doing?</li><li>What are they afraid of?</li><li>What do they cherish most in the world?</li></ul>",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Midnight,
		level: 6,
		isHomebrew: false,
	},
	"MIDNIGHT-6-2": {
		id: "MIDNIGHT-6-2",
		title: "Mass Disguise",
		description:
			"When you have a few minutes of silence to focus, you can mark a *Stress* to change the appearance of every willing target close to you, lasting for one hour. The new form must share a general body structure and size, and can be somebody or something you've seen before or entirely fabricated.\nA disguised creature's Presence rolls to shrug off scrutiny have Advantage.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Midnight,
		level: 6,
		isHomebrew: false,
	},
	"MIDNIGHT-7-1": {
		id: "MIDNIGHT-7-1",
		title: "Midnight Touched",
		description:
			"When a majority of the domain cards in your loadout are from the *Midnight* domain:<ul><li>Whenever you succeed with *Fear*, you gain a *Hope*.</li><li>If your *Fear* die ever rolls a 1 or 2, you may reroll it once and take the new result instead.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Midnight,
		level: 7,
		isHomebrew: false,
	},
	"MIDNIGHT-7-2": {
		id: "MIDNIGHT-7-2",
		title: "Phantom Dodge",
		description:
			"When you successfully evade physical damage, you can choose to envelope yourself in shadow, becoming Hidden and teleporting to anywhere in close range of the target that attacked you. You remain Hidden until the next time you make an action roll.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 7,
		isHomebrew: false,
	},
	"MIDNIGHT-8-1": {
		id: "MIDNIGHT-8-1",
		title: "Shadowhunter",
		description:
			"Under the cover of shadow, your prowess is enhanced. While you are shrouded in low light or darkness, you gain +1 Proficiency and add half your Spellcast trait to your Evasion (rounded up).",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Midnight,
		level: 8,
		isHomebrew: false,
	},
	"MIDNIGHT-8-2": {
		id: "MIDNIGHT-8-2",
		title: "Spellcharge",
		description:
			"When you should take magic damage, place tokens on this card equal to the number of hit points that damage would do. Then, reduce the incoming damage in half (rounded up).When you make a successful attack roll against a target, you can spend any number of the tokens from this card to deal an additional *1d6* magic damage per token. On your next rest, clear all tokens.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 8,
		isHomebrew: false,
	},
	"MIDNIGHT-9-1": {
		id: "MIDNIGHT-9-1",
		title: "Night Terror",
		description:
			"Once per long rest, use an action to choose any targets within very close range. For them, your visage changes into something of nightmarish horror. They must make a successful *Reaction Roll (16)* or become temporarily Horrified. While Horrified, they are Vulnerable. Steal an amount of *Fear* from the GM equal to the number of targets that are Horrified (or as many as they have, if it's not enough). For each *Fear* stolen, roll a *d6* and deal that much damage to each Horrified target. Discard the stolen *Fear*.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Midnight,
		level: 9,
		isHomebrew: false,
	},
	"MIDNIGHT-9-2": {
		id: "MIDNIGHT-9-2",
		title: "Twilight Toll",
		description:
			"Choose a target within far range to mark. Each time you succeed on any *Action Roll* against them that doesn't result in making a damage roll, place a token on this card. When you roll damage against this target, you can spend any number of tokens to deal an additional *1d12* per token spent. You may only hold Twilight Toll on one creature at a time.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Midnight,
		level: 9,
		isHomebrew: false,
	},
	"MIDNIGHT-10-1": {
		id: "MIDNIGHT-10-1",
		title: "Eclipse",
		description:
			"Make a *Spellcast Roll (16)*. On a success, once per long rest, spend *3 Hope* to plunge the entire area within far range into magical shadow that moves with you. Whenever you or an ally within this shadow should be damaged by an attack or spell, roll *1d6*. On a result of *5+*, the attack or spell misses.\nIn addition, when you or an ally rolls a successful *Attack Roll* with Hope against an enemy that is within this shadow, the enemy takes a *Stress*.\nThis spell lasts for until the GM spends a *Fear*, or you take Severe damage.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Midnight,
		level: 10,
		isHomebrew: false,
	},
	"MIDNIGHT-10-2": {
		id: "MIDNIGHT-10-2",
		title: "Specter of the Dark",
		description:
			"Mark a *Stress* to move like a ghost. While in this form, you are visible but can float and pass through solid objects for a number of minutes equal to your *Spellcast Trait*. During this time, you are immune to physical damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Midnight,
		level: 10,
		isHomebrew: false,
	},
	"SAGE-1-1": {
		id: "SAGE-1-1",
		title: "Gifted Tracker",
		description:
			"Make a *Spellcast Roll* to track or ask the GM one question you'd be able to learn about a specific creature or group of creatures based on signs of their passage. If you spend a *Hope* before the roll, you can double your spellcast trait as the modifier.\nIf you encounter any creatures you've tracked, your *Evasion* against them is *+1*.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Sage,
		level: 1,
		isHomebrew: false,
	},
	"SAGE-1-2": {
		id: "SAGE-1-2",
		title: "Nature's Tongue",
		description:
			"You can speak the language of the hidden, natural world. When you want to speak to the plants and animals around you, make an *Instinct Roll (12)*. On a success, they'll give you the information they know. With *Fear*, their knowledge might be limited or come at a cost.\nIn addition, whenever you make a *Spellcast Roll* while within a natural environment, you may spend a *Hope* before the roll to add *+1* to the result.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Sage,
		level: 1,
		isHomebrew: false,
	},
	"SAGE-1-3": {
		id: "SAGE-1-3",
		title: "Vicious Entangle",
		description:
			"Make a *Spellcast Roll* against a target within far range. On a success, roots and vines reach out from the ground and temporarily Restrain them, dealing *1d8* physical damage.\nOn a success, you may also spend a *Hope* to temporarily Restrain any enemies very close to your target.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 1,
		isHomebrew: false,
	},
	"SAGE-2-1": {
		id: "SAGE-2-1",
		title: "Conjure Swarm",
		description:
			"*Tekaira Armored Beetles*: Mark an Armor Slot to encircle yourself in beetles. When you take damage, you can reduce the damage by your Armor Score. Anytime you reduce damage in this way, the beetles will dissipate unless you spend a *Hope* to keep them active.\n\n*Fire Flies*: Make a *Spellcast Roll* against any close enemies. On a success, spend a *Hope* to have the fire flies swarm them, doing *2d8* magic damage to all targets you succeeded against.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 2,
		isHomebrew: false,
	},
	"SAGE-2-2": {
		id: "SAGE-2-2",
		title: "Natural Familiar",
		description:
			"Spend a *Hope* to summon a small nature spirit or forest critter to your side until your next short rest, you use this spell again, or until it takes damage. If you spend an additional *Hope*, they can be a familiar that flies. You can communicate with it, you may make a *Spellcast Roll* to command it to perform simple tasks, and you can mark a *Stress* to see through its eyes.\nWhile this creature is summoned, when you deal damage to an enemy the critter is in melee range with, you deal an additional *1d6* physical damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 2,
		isHomebrew: false,
	},
	"SAGE-3-1": {
		id: "SAGE-3-1",
		title: "Corrosive Projectile",
		description:
			"Make a *Spellcast Roll* against a target within far range. On a success, mark a *Stress* to deal d6 magic damage using your proficiency. The target's *Difficulty* value is temporarily reduced by *1*.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 3,
		isHomebrew: false,
	},
	"SAGE-3-2": {
		id: "SAGE-3-2",
		title: "Towering Stalk",
		description:
			"You can conjure a thick, twisting stalk within close range that can be easily climbed. It's height can grow up to far range.\nWhen you conjure it, you may also mark a *Stress* to use it as an attack. If you do, make a *Spellcast Roll* against any group of targets within close range. It erupts beneath any you're successful against, lifting them into the air and dropping them for *3d8* physical damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 3,
		isHomebrew: false,
	},
	"SAGE-4-1": {
		id: "SAGE-4-1",
		title: "Death Grip",
		description:
			"Choose an option below and make a *Spellcast Roll* against the target in close range. On a success, vines reach out from your hands, causing the chosen effect and making them <i>Restrained</i>.<ul><li>Pull the target into melee range of you or pull yourself into melee range with it.</li><li>Constrict the target to deal *2 Stress*.</li><li>Any enemies between you and the target must make a Reaction Roll (13) or be hit by vines, dealing 3d6 physical damage.</li></ul>",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 4,
		isHomebrew: false,
	},
	"SAGE-4-2": {
		id: "SAGE-4-2",
		title: "Healing Field",
		description:
			"Once per long rest, you can use an action to conjure a field of small, healing plants around you. Everywhere within close range of you bursts to life with vibrant nature, causing you and your allies in the area to immediately heal one Hit Point.\nSpend a *Hope* to increase the healing power of this spell to two Hit Points.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Sage,
		level: 4,
		isHomebrew: false,
	},
	"SAGE-5-1": {
		id: "SAGE-5-1",
		title: "Thorn Skin",
		description:
			"Once per short rest, spend a Hope while touching a willing creature and place a number of tokens equal to your Spellcast Trait on this card. Whenever the target takes damage, you can remove any number of these tokens to roll that number of *d6*s. Then reduce the incoming damage by that amount and, if the attacker is in melee, deal that amount of damage back to them.\nWhen you take a rest, clear all tokens.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 5,
		isHomebrew: false,
	},
	"SAGE-5-2": {
		id: "SAGE-5-2",
		title: "Wild Fortress",
		description:
			"Make a *Spellcast Roll (13)* to grow a natural barricade in the shape of a dome for you and up to one ally to hide within. You immediately become hidden as long as you stay within, but may reveal yourself out the top of the dome to make ranged attacks. The dome has the damage thresholds below and lasts until it takes three Hit Points. Place tokens on this card to represent marking Hit Points.\n\n*Minor 1* | *Major 15* | *Severe 30*",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 5,
		isHomebrew: false,
	},
	"SAGE-6-1": {
		id: "SAGE-6-1",
		title: "Conjured Steeds",
		description:
			"Spend a *Hope* to conjure a number of magical steeds (horses, camels, elephants, etc.) up to your level that you and allies can ride upon until your next long rest or the steed takes any damage. These will double your land speed when traveling and let you move to somewhere within far range without having to roll when in danger. Any *Attack Rolls* made atop the steeds are at *-2*, but add *+2* to their damage rolls.",
		type: CardType.Spell,
		recall: 0,
		domain: Domain.Sage,
		level: 6,
		isHomebrew: false,
	},
	"SAGE-6-2": {
		id: "SAGE-6-2",
		title: "Forager",
		description:
			"As an additional downtime move, you may roll *1d6* to see what you forage. Work with the GM to describe it, and add it to your inventory as a Consumable. Your party may carry up to five foraged Consumables at a time.<ol><li>A unique food. (Clear *2 Stress*)</li><li>A beautiful relic. (Earn *2 Hope*)</li><li>An arcane rune. (*+2* to a *Spellcast Roll*)</li><li>A healing vial. (Clear 2 Hit Points)</li><li>A luck charm. (Reroll all Duality or Damage Dice)</li><li>You may choose one of the above options.</li></ol>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Sage,
		level: 6,
		isHomebrew: false,
	},
	"SAGE-7-1": {
		id: "SAGE-7-1",
		title: "Wild Surge",
		description:
			"Once per long rest, mark a *Stress* to channel the natural world around you and use it to enhance yourself. Describe how your appearance changes, then place a *d6* on this card at a value of *6*.\nWhile the Wild Surge no die is active, it adds its value to every *Action Roll* you make. After you add its value to a roll, reduce it by *1*. When the die's value reaches *0* or you take a rest, this form drops and you must mark an additional *Stress*.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Sage,
		level: 7,
		isHomebrew: false,
	},
	"SAGE-7-2": {
		id: "SAGE-7-2",
		title: "Sage Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Sage domain:<ul><li>When you are in a natural environment, you always take *+1* to your *Spellcast Rolls*.</li><li>Once per short rest, before you roll, treat your *Agility* or *Instinct* Trait as though it were double its current value.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Sage,
		level: 7,
		isHomebrew: false,
	},
	"SAGE-8-1": {
		id: "SAGE-8-1",
		title: "Forest Sprites",
		description:
			"Make a *Spellcast Roll (13)*. On a success, spend any number of *Hope* to create an equal number of small Forest Sprites that appear wherever you choose within far range, distracting enemies and aiding allies. Describe what form they take.\nAttack Rolls against an enemy within melee range of a Sprite gain +3. Any allies who mark an Armor Slot while in melee range of a Sprite add +3 to their Armor Score.\nA Sprite vanishes after granting a bonus or taking any damage.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Sage,
		level: 8,
		isHomebrew: false,
	},
	"SAGE-8-2": {
		id: "SAGE-8-2",
		title: "Rejuvenation Barrier",
		description:
			"Make a *Spellcast Roll (15)*. On a success, once per short rest, you can create a temporary barrier of protective energy around you. You and all allies within very close range of you when it is first cast heal *1d4 Hit Points*. While the barrier is up, you and all allies within have Resistance to physical damage.\nThis barrier will follow you as you move.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 8,
		isHomebrew: false,
	},
	"SAGE-9-1": {
		id: "SAGE-9-1",
		title: "Fane of the Wilds",
		description:
			"After a long rest, place a number of tokens equal to how many Sage Domain cards you have in your Loadout and Vault on this card.\nWhenever you would make a *Spellcast Roll*, you may spend any number of these tokens before the roll to add *+1* to the result per token.\nWhenever you roll a Critical Success on a *Spellcast Roll* for a Sage spell, gain a token.\nWhen you take a long rest, clear all tokens.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Sage,
		level: 9,
		isHomebrew: false,
	},
	"SAGE-9-2": {
		id: "SAGE-9-2",
		title: "Plant Dominion",
		description:
			"Make a *Spellcast Roll (18)*. On a success, you reshape the natural world, changing the surrounding plant life within very far distance of you. You can grow trees instantly, clear a path through dense vines, create a wall of thick roots, etc.\nIf you create a hostile environment, anyone who moves into or through it takes *5d10* physical damage.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Sage,
		level: 9,
		isHomebrew: false,
	},
	"SAGE-10-1": {
		id: "SAGE-10-1",
		title: "Force of Nature",
		description:
			"You can mark a Stress to transform into a hulking nature spirit, gaining the following benefits:\nYou gain *+2* Strength, *+2* Agility, and *+2* Finesse.<ul><li>Whenever you successfully hit with an Attack or Spell, you deal an additional 1d10 damage</li><li>When you defeat a creature within close range, you absorb them and clear an Armor Slot.</li><li>You cannot be restrained.</li></ul>\nBefore you make an *Action Roll*, you must spend a *Hope*. If you cannot, you revert to your normal form.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Sage,
		level: 10,
		isHomebrew: false,
	},
	"SAGE-10-2": {
		id: "SAGE-10-2",
		title: "Tempest",
		description:
			"Choose one of the following tempests and make a *Spellcast Roll* against all targets in far range. Any you are successful against experience its effects until the GM spends a *Fear* to end this spell:\n<i>Blizzard</i> - Deal *2d20* magic damage and make them vulnerable.\n<i>Hurricane</i> - Immediately deal *3d10* magic damage. Choose a direction the wind is blowing. Targets can't move against the wind.\n<i>Sandstorm</i> - Deal *5d6* magic damage and attacks beyond melee range are now at disadvantage.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Sage,
		level: 10,
		isHomebrew: false,
	},
	"SPLENDOR-1-1": {
		id: "SPLENDOR-1-1",
		title: "Bolt Beacon",
		description:
			"Make a Spellcast Roll against a target within far range. On a success, spend a Hope to send a bolt of shimmering light towards them. Treat it like a ranged weapon, dealing d8 magic damage using your proficiency that makes them glow brightly and become temporarily Vulnerable.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 1,
		isHomebrew: false,
	},
	"SPLENDOR-1-2": {
		id: "SPLENDOR-1-2",
		title: "Mending Touch",
		description:
			"You lay your hands upon a creature and channel healing magic to help close their wounds. When you can take a few minutes to focus on the person you're helping, spend 2 Hope and heal a Hit Point or a Stress.\nOnce per long rest, when you spend this healing time learning something new about them or revealing something about yourself, the 2 Hope you spend heals 2 Hit Points or 2 Stress instead.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 1,
		isHomebrew: false,
	},
	"SPLENDOR-1-3": {
		id: "SPLENDOR-1-3",
		title: "Reassurance",
		description:
			"Once per short rest, after an ally attempts an *Action Roll*, but before the consequences take place, you may offer assistance or words of support. When you do, they may reroll their dice. They must accept the result of this new roll.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Splendor,
		level: 1,
		isHomebrew: false,
	},
	"SPLENDOR-2-1": {
		id: "SPLENDOR-2-1",
		title: "Final Words",
		description:
			"Make a Spellcast Roll (13). On a success, you can infuse a moment of life into a corpse in order to speak with it. If the result is with Hope, it will answer up to three questions. If the result is with Fear, only one. Once the spell ends or on a failure, the body will turn to dust.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 2,
		isHomebrew: false,
	},
	"SPLENDOR-2-2": {
		id: "SPLENDOR-2-2",
		title: "Healing Hands",
		description:
			"Make a Spellcast Roll (13) and target a creature other than yourself in melee. On a success, mark a Stress to heal the target 2 Hit Points or 2 Stress. On a failure, mark a Stress to heal the target 1 Hit Point or 1 Stress. You can't heal the same target again until after your next short rest.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 2,
		isHomebrew: false,
	},
	"SPLENDOR-3-1": {
		id: "SPLENDOR-3-1",
		title: "Conviction",
		description:
			"You speak with an unmatched power and grace. When you attempt to use this candor to de-escalate a violent situation or get someone to follow your lead, roll with advantage.\nYour conviction also emboldens you in moments of duress. When all of your Stress is marked, your attacks are made with +1 Proficiency.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Splendor,
		level: 3,
		isHomebrew: false,
	},
	"SPLENDOR-3-2": {
		id: "SPLENDOR-3-2",
		title: "Second Wind",
		description:
			"Once per short rest, when you make a successful strike against an enemy, you may clear 3 Stress or one Hit Point. On a success with Hope, you may also clear 3 Stress or one Hit Point of an ally who is within close range of you.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Splendor,
		level: 3,
		isHomebrew: false,
	},
	"SPLENDOR-4-1": {
		id: "SPLENDOR-4-1",
		title: "Divination",
		description:
			"Once per long rest, you may spend 3 Hope to reach out to the forces beyond and ask one question about an event, person, place, or situation in the near future. Your vision of the world will momentarily twist and shape around you to show the answer, though it may be cryptic, obscured, or partial.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 4,
		isHomebrew: false,
	},
	"SPLENDOR-4-2": {
		id: "SPLENDOR-4-2",
		title: "Life Ward",
		description:
			"Use an action to spend 3 Hope and point at a close ally. They are marked with a glowing sigil of protection. If this ally is ever required to make a death move for any reason, they ignore it and clear one hit point.\nThis spell ends when it saves the target from a Death Move, it is cast on another target, or when you take a long rest.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 4,
		isHomebrew: false,
	},
	"SPLENDOR-5-1": {
		id: "SPLENDOR-5-1",
		title: "Shape Material",
		description:
			"Mark a Hope to adjust a section of natural material you are touching (like stone, ice, wood, etc) into a shape that suits your purpose. This material area can be no larger than you. Examples include forming a rudimentary tool or weapon, creating a door or passage, etc.\nYou can only affect the material within close range of where you are touching it.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 5,
		isHomebrew: false,
	},
	"SPLENDOR-5-2": {
		id: "SPLENDOR-5-2",
		title: "Smite",
		description:
			"Spend 3 Hope to charge up a powerful smite. On the next successful attack, double your Proficiency on the damage roll, and this attack deals magic damage, regardless of the weapon's damage type.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 5,
		isHomebrew: false,
	},
	"SPLENDOR-6-1": {
		id: "SPLENDOR-6-1",
		title: "Restoration",
		description:
			"After a long rest, place a number of tokens equal to your Spellcast Trait on this card. You can touch a creature and spend any number of tokens to heal them for 2 Hit Points per token. You can also spend a token when touching a creature to clear a Stress, end the Vulnerable condition, a disease, or a magical ailment (though the GM might require additional tokens depending on the power of the ailment). If the action tracker is out, any spent tokens are added to it.\nWhen you take a long rest, clear all tokens.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 6,
		isHomebrew: false,
	},
	"SPLENDOR-6-2": {
		id: "SPLENDOR-6-2",
		title: "Zone of Protection",
		description:
			"Make a Spellcast Roll (16). On a success, once per long rest, you can designate a point within far range of you and create a visible zone of protection there for all allies within very close range of that point. When you do, place a d8 on this card at its highest value. When taking damage, any allies in this zone automatically reduce it by the die's value. Then reduce the die's value by 1. This spell ends when the die reaches 0.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 6,
		isHomebrew: false,
	},
	"SPLENDOR-7-1": {
		id: "SPLENDOR-7-1",
		title: "Healing Strike",
		description:
			"Whenever you do damage to an enemy, you may spend a *Hope* to heal a single Hit Point on an ally within close range of you.",
		type: CardType.Spell,
		recall: 1,
		domain: Domain.Splendor,
		level: 7,
		isHomebrew: false,
	},
	"SPLENDOR-7-2": {
		id: "SPLENDOR-7-2",
		title: "Splendor Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Splendor domain:<ul><li>Increase your Major Damage Threshold by +3.</li><li>Once per long rest, when incoming damage would require you to take a certain number of Hit Points, you may choose to take that much Stress or spend that much Hope instead.</li></ul>",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Splendor,
		level: 7,
		isHomebrew: false,
	},
	"SPLENDOR-8-1": {
		id: "SPLENDOR-8-1",
		title: "Shield Aura",
		description:
			"Mark a Stress to cast Shield Aura on a creature you can touch. Whenever they use an Armor Slot, they roll a d12 and add its value to their Armor Score. If the d12 result is equal to or above their current level, this spell ends. If the d12 result is below their current level, it stays active.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 8,
		isHomebrew: false,
	},
	"SPLENDOR-8-2": {
		id: "SPLENDOR-8-2",
		title: "Stunning Sunlight",
		description:
			"Make a Spellcast Roll against any enemies in front of you within far distance as you unleash powerful rays of burning sunlight. Spend a Hope for each enemy you succeed against that you want to affect, and they must make a Reaction Roll (14).\nOn a success, they take 4d20 magic damage.\nOn a failure, they take 4d20 magic damage and are temporarily stunned, keeping them from acting until the condition is cleared.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 8,
		isHomebrew: false,
	},
	"SPLENDOR-9-1": {
		id: "SPLENDOR-9-1",
		title: "Overwhelming Aura",
		description:
			"Make a Spellcast Roll (15) to temporarily embody powerful presence. On a success, spend 2 Hope to make your Presence score equal to your Spellcast Trait until your next long rest.\nWhile you have Overwhelming Aura active, the GM must always spend a Fear to target you with an attack.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 9,
		isHomebrew: false,
	},
	"SPLENDOR-9-2": {
		id: "SPLENDOR-9-2",
		title: "Salvation Beam",
		description:
			"Make a Spellcast Roll (15). On a success, mark any amount of Stress to clear that many Hit Points on a line of allies within far range.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 9,
		isHomebrew: false,
	},
	"SPLENDOR-10-1": {
		id: "SPLENDOR-10-1",
		title: "Invigoration",
		description:
			"When you or an ally close to you has used an ability or spell that has an exhaustion limit (once per short rest, once per long rest, etc.), you and any of these allies may spend any amount of Hope to roll that many d6. On a 6, you or your ally regain use of that ability or spell.\nThis spell doesn't work on any abilities or spells that have been permanently placed in your Vault.",
		type: CardType.Spell,
		recall: 4,
		domain: Domain.Splendor,
		level: 10,
		isHomebrew: false,
	},
	"SPLENDOR-10-2": {
		id: "SPLENDOR-10-2",
		title: "Resurrection",
		description:
			"Make a Spellcast Roll (20). On a success, you may restore one creature who has been dead no longer than 100 years. Then roll a 1d6. On a 1-5, put this card into your Vault permanently.\nOn a failure, this cannot be attempted again for at least a week, and the consequences of failing such powerful magic can have unexpected effects on the dead.",
		type: CardType.Spell,
		recall: 2,
		domain: Domain.Splendor,
		level: 10,
		isHomebrew: false,
	},
	"VALOR-1-1": {
		id: "VALOR-1-1",
		title: "Bare Bones",
		description:
			"While this card is in your loadout, if you choose not to equip Armor, you have an Armor Score equal to 3 + your level.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Valor,
		level: 1,
		isHomebrew: false,
	},
	"VALOR-1-2": {
		id: "VALOR-1-2",
		title: "Forceful Push",
		description:
			"When you make a successful melee attack, you can push the target out of melee range and spend a Hope to make them temporarily Vulnerable.\nOn a success with Hope, add an additional 1d6 to your damage dice on this attack.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Valor,
		level: 1,
		isHomebrew: false,
	},
	"VALOR-1-3": {
		id: "VALOR-1-3",
		title: "I am your Shield",
		description:
			"When an ally very close to you is going to take damage, you may mark a stress to stand in its way and take the damage instead. Reduce the damage by a value equal to your Strength Trait. You may also reduce the damage by spending armor slots.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 1,
		isHomebrew: false,
	},
	"VALOR-2-1": {
		id: "VALOR-2-1",
		title: "Body Basher",
		description:
			"You use the full force of your body in the fight. On a successful melee attack, always add your Strength Trait to your damage total.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 2,
		isHomebrew: false,
	},
	"VALOR-2-2": {
		id: "VALOR-2-2",
		title: "Bold Presence",
		description:
			"Whenever you make a Presence roll against a hostile target, you can also add your Strength trait to the roll.",
		type: CardType.Ability,
		recall: 0,
		domain: Domain.Valor,
		level: 2,
		isHomebrew: false,
	},
	"VALOR-3-1": {
		id: "VALOR-3-1",
		title: "Critical Inspiration",
		description:
			"When you or an ally close to you rolls a critical success on an Attack Roll, whoever rolled the critical success may immediately clear a Hit Point or an additional Stress.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 3,
		isHomebrew: false,
	},
	"VALOR-3-2": {
		id: "VALOR-3-2",
		title: "Lean on Me",
		description:
			"Once per long rest, when a character has failed at an action they were attempting, if you console or inspire them, you both clear 2 Stress.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 3,
		isHomebrew: false,
	},
	"VALOR-4-1": {
		id: "VALOR-4-1",
		title: "Goad them on",
		description:
			"Make a Presence roll against a target. On a success, the target takes a Stress and the next time they act, they target you with disadvantage.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 4,
		isHomebrew: false,
	},
	"VALOR-4-2": {
		id: "VALOR-4-2",
		title: "Support Tank",
		description:
			"When an ally close to you fails a roll, you may spend 2 Hope to allow them to reroll either their Hope or Fear die and take the new result instead.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Valor,
		level: 4,
		isHomebrew: false,
	},
	"VALOR-5-1": {
		id: "VALOR-5-1",
		title: "Armorer",
		description:
			"Your Armor Score increases by +1 while you are wearing armor and this card is in your loadout.\nDuring a short rest, if you choose to take the Repair Armor downtime action, everybody in your party also clears one additional Armor Slot.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 5,
		isHomebrew: false,
	},
	"VALOR-5-2": {
		id: "VALOR-5-2",
		title: "Rousing Strike",
		description:
			"Once per short rest, when you roll a Critical Success on an Attack Roll, you and all allies that can see or hear you may clear a Hit Point or 1d4 Stress.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 5,
		isHomebrew: false,
	},
	"VALOR-6-1": {
		id: "VALOR-6-1",
		title: "Inevitable",
		description:
			"Whenever you fail an Action Roll, your next Action Roll has Advantage.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 6,
		isHomebrew: false,
	},
	"VALOR-6-2": {
		id: "VALOR-6-2",
		title: "Rise up",
		description:
			"While this card is in your loadout, make your Minor Threshold the value of your Strength trait.",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Valor,
		level: 6,
		isHomebrew: false,
	},
	"VALOR-7-1": {
		id: "VALOR-7-1",
		title: "Shrug it off",
		description:
			"When you would take damage, you may mark a Stress to reduce the severity of the damage by one Threshold. When you do, roll 1d6. If the result is a 2 or below, place this card into your Vault.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 7,
		isHomebrew: false,
	},
	"VALOR-7-2": {
		id: "VALOR-7-2",
		title: "Valor Touched",
		description:
			"When a majority of the domain cards in your loadout are from the Valor domain:<ul><li>Your Armor Score increases by +2 while this ability is in your loadout.</li><li>When you mark one or more Hit Points from damage, roll 1d6. If you get a 5+, you can clear a Stress.</li></ul>",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 7,
		isHomebrew: false,
	},
	"VALOR-8-1": {
		id: "VALOR-8-1",
		title: "Full Surge",
		description:
			"Once per long rest, mark 3 Stress to push your body to its limits, increasing all of your Character Traits by +2. This lasts until your next rest.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 8,
		isHomebrew: false,
	},
	"VALOR-8-2": {
		id: "VALOR-8-2",
		title: "Ground Pound",
		description:
			"Spend 2 Hope to strike the ground where you stand and make a Strength Roll against any enemies within very close range of you. All you succeed against are thrown back to far range and must make a Reaction Roll (17). On a failure, they also take 4d10 damage. On a success, they take half damage instead (rounded up).",
		type: CardType.Ability,
		recall: 2,
		domain: Domain.Valor,
		level: 8,
		isHomebrew: false,
	},
	"VALOR-9-1": {
		id: "VALOR-9-1",
		title: "Hold the Line",
		description:
			"Spend a Hope to take a defensive stance that lasts until you move or fail a roll with Fear. While in this stance, note the area within close range of you. If any enemy ever occupies that area, they are immediately put into melee with you and are temporarily Restrained.\nThe Restrained condition can only be ended if the GM spends a Fear to do it.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 9,
		isHomebrew: false,
	},
	"VALOR-9-2": {
		id: "VALOR-9-2",
		title: "Lead by Example",
		description:
			"Whenever you mark an Armor Slot, you can choose an ally who can see or hear you to gain a Hope or clear a Stress.",
		type: CardType.Ability,
		recall: 3,
		domain: Domain.Valor,
		level: 9,
		isHomebrew: false,
	},
  "VALOR-10-1": {
		id: "VALOR-10-1",
		title: "Unbreakable",
		description:
			"When you mark your last Hit Point, instead of making a death move, you may roll a 1d6 and clear that many marked Hit Points. Then put this card into your Vault.",
		type: CardType.Ability,
		recall: 4,
		domain: Domain.Valor,
		level: 10,
		isHomebrew: false,
	},
	"VALOR-10-2": {
		id: "VALOR-10-2",
		title: "Unyielding Armor",
		description:
			"Anytime you mark an Armor Slot, roll an amount of d6s equal to the Armor Slots you currently have marked. If any result in a 6, you don't have to mark it.",
		type: CardType.Ability,
		recall: 1,
		domain: Domain.Valor,
		level: 10,
		isHomebrew: false,
	},
};
